export const dataPage = [
  {
    id: 1,
    text_uthmani: "بِسْمِ",
    code_v2: "ﱁ",
    text_qpc_hafs: "بِسۡمِ",
    line_number: 2,
    location_v2: "1:1:1",
    verse_key: "1:1",
    char_type_name: "word",
    verse_id: 1,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_001_001.mp3",
  },
  {
    id: 2,
    text_uthmani: "ٱللَّهِ",
    code_v2: "ﱂ",
    text_qpc_hafs: "ٱللَّهِ",
    line_number: 2,
    location_v2: "1:1:2",
    verse_key: "1:1",
    char_type_name: "word",
    verse_id: 1,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_001_002.mp3",
  },
  {
    id: 3,
    text_uthmani: "ٱلرَّحْمَـٰنِ",
    code_v2: "ﱃ",
    text_qpc_hafs: "ٱلرَّحۡمَٰنِ",
    line_number: 2,
    location_v2: "1:1:3",
    verse_key: "1:1",
    char_type_name: "word",
    verse_id: 1,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_001_003.mp3",
  },
  {
    id: 4,
    text_uthmani: "ٱلرَّحِيمِ",
    code_v2: "ﱄ",
    text_qpc_hafs: "ٱلرَّحِيمِ",
    line_number: 2,
    location_v2: "1:1:4",
    verse_key: "1:1",
    char_type_name: "word",
    verse_id: 1,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_001_004.mp3",
  },
  {
    id: 5,
    text_uthmani: "١",
    code_v2: "ﱅ",
    text_qpc_hafs: "١",
    line_number: 2,
    location_v2: "1:1:5",
    verse_key: "1:1",
    char_type_name: "end",
    verse_id: 1,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
  {
    id: 1130,
    text_uthmani: "ٱلْحَمْدُ",
    code_v2: "ﱆ",
    text_qpc_hafs: "ٱلۡحَمۡدُ",
    line_number: 3,
    location_v2: "1:2:1",
    verse_key: "1:2",
    char_type_name: "word",
    verse_id: 2,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_002_001.mp3",
  },
  {
    id: 1131,
    text_uthmani: "لِلَّهِ",
    code_v2: "ﱇ",
    text_qpc_hafs: "لِلَّهِ",
    line_number: 3,
    location_v2: "1:2:2",
    verse_key: "1:2",
    char_type_name: "word",
    verse_id: 2,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_002_002.mp3",
  },
  {
    id: 1132,
    text_uthmani: "رَبِّ",
    code_v2: "ﱈ",
    text_qpc_hafs: "رَبِّ",
    line_number: 3,
    location_v2: "1:2:3",
    verse_key: "1:2",
    char_type_name: "word",
    verse_id: 2,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_002_003.mp3",
  },
  {
    id: 1133,
    text_uthmani: "ٱلْعَـٰلَمِينَ",
    code_v2: "ﱉ",
    text_qpc_hafs: "ٱلۡعَٰلَمِينَ",
    line_number: 3,
    location_v2: "1:2:4",
    verse_key: "1:2",
    char_type_name: "word",
    verse_id: 2,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_002_004.mp3",
  },
  {
    id: 1134,
    text_uthmani: "٢",
    code_v2: "ﱊ",
    text_qpc_hafs: "٢",
    line_number: 3,
    location_v2: "1:2:5",
    verse_key: "1:2",
    char_type_name: "end",
    verse_id: 2,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
  {
    id: 2953,
    text_uthmani: "ٱلرَّحْمَـٰنِ",
    code_v2: "ﱋ",
    text_qpc_hafs: "ٱلرَّحۡمَٰنِ",
    line_number: 4,
    location_v2: "1:3:1",
    verse_key: "1:3",
    char_type_name: "word",
    verse_id: 3,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_003_001.mp3",
  },
  {
    id: 2954,
    text_uthmani: "ٱلرَّحِيمِ",
    code_v2: "ﱌ",
    text_qpc_hafs: "ٱلرَّحِيمِ",
    line_number: 4,
    location_v2: "1:3:2",
    verse_key: "1:3",
    char_type_name: "word",
    verse_id: 3,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_003_002.mp3",
  },
  {
    id: 2955,
    text_uthmani: "٣",
    code_v2: "ﱍ",
    text_qpc_hafs: "٣",
    line_number: 4,
    location_v2: "1:3:3",
    verse_key: "1:3",
    char_type_name: "end",
    verse_id: 3,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
  {
    id: 3252,
    text_uthmani: "مَـٰلِكِ",
    code_v2: "ﱎ",
    text_qpc_hafs: "مَٰلِكِ",
    line_number: 4,
    location_v2: "1:4:1",
    verse_key: "1:4",
    char_type_name: "word",
    verse_id: 4,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_004_001.mp3",
  },
  {
    id: 3253,
    text_uthmani: "يَوْمِ",
    code_v2: "ﱏ",
    text_qpc_hafs: "يَوۡمِ",
    line_number: 4,
    location_v2: "1:4:2",
    verse_key: "1:4",
    char_type_name: "word",
    verse_id: 4,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_004_002.mp3",
  },
  {
    id: 3254,
    text_uthmani: "ٱلدِّينِ",
    code_v2: "ﱐ",
    text_qpc_hafs: "ٱلدِّينِ",
    line_number: 4,
    location_v2: "1:4:3",
    verse_key: "1:4",
    char_type_name: "word",
    verse_id: 4,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_004_003.mp3",
  },
  {
    id: 3255,
    text_uthmani: "٤",
    code_v2: "ﱑ",
    text_qpc_hafs: "٤",
    line_number: 4,
    location_v2: "1:4:4",
    verse_key: "1:4",
    char_type_name: "end",
    verse_id: 4,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
  {
    id: 5334,
    text_uthmani: "إِيَّاكَ",
    code_v2: "ﱒ",
    text_qpc_hafs: "إِيَّاكَ",
    line_number: 5,
    location_v2: "1:5:1",
    verse_key: "1:5",
    char_type_name: "word",
    verse_id: 5,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_005_001.mp3",
  },
  {
    id: 5335,
    text_uthmani: "نَعْبُدُ",
    code_v2: "ﱓ",
    text_qpc_hafs: "نَعۡبُدُ",
    line_number: 5,
    location_v2: "1:5:2",
    verse_key: "1:5",
    char_type_name: "word",
    verse_id: 5,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_005_002.mp3",
  },
  {
    id: 5336,
    text_uthmani: "وَإِيَّاكَ",
    code_v2: "ﱔ",
    text_qpc_hafs: "وَإِيَّاكَ",
    line_number: 5,
    location_v2: "1:5:3",
    verse_key: "1:5",
    char_type_name: "word",
    verse_id: 5,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_005_003.mp3",
  },
  {
    id: 5337,
    text_uthmani: "نَسْتَعِينُ",
    code_v2: "ﱕ",
    text_qpc_hafs: "نَسۡتَعِينُ",
    line_number: 5,
    location_v2: "1:5:4",
    verse_key: "1:5",
    char_type_name: "word",
    verse_id: 5,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_005_004.mp3",
  },
  {
    id: 5338,
    text_uthmani: "٥",
    code_v2: "ﱖ",
    text_qpc_hafs: "٥",
    line_number: 5,
    location_v2: "1:5:5",
    verse_key: "1:5",
    char_type_name: "end",
    verse_id: 5,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
  {
    id: 6844,
    text_uthmani: "ٱهْدِنَا",
    code_v2: "ﱗ",
    text_qpc_hafs: "ٱهۡدِنَا",
    line_number: 5,
    location_v2: "1:6:1",
    verse_key: "1:6",
    char_type_name: "word",
    verse_id: 6,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_006_001.mp3",
  },
  {
    id: 6845,
    text_uthmani: "ٱلصِّرَٰطَ",
    code_v2: "ﱘ",
    text_qpc_hafs: "ٱلصِّرَٰطَ",
    line_number: 6,
    location_v2: "1:6:2",
    verse_key: "1:6",
    char_type_name: "word",
    verse_id: 6,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_006_002.mp3",
  },
  {
    id: 6846,
    text_uthmani: "ٱلْمُسْتَقِيمَ",
    code_v2: "ﱙ",
    text_qpc_hafs: "ٱلۡمُسۡتَقِيمَ",
    line_number: 6,
    location_v2: "1:6:3",
    verse_key: "1:6",
    char_type_name: "word",
    verse_id: 6,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_006_003.mp3",
  },
  {
    id: 6847,
    text_uthmani: "٦",
    code_v2: "ﱚ",
    text_qpc_hafs: "٦",
    line_number: 6,
    location_v2: "1:6:4",
    verse_key: "1:6",
    char_type_name: "end",
    verse_id: 6,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
  {
    id: 8411,
    text_uthmani: "صِرَٰطَ",
    code_v2: "ﱛ",
    text_qpc_hafs: "صِرَٰطَ",
    line_number: 6,
    location_v2: "1:7:1",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_001.mp3",
  },
  {
    id: 8412,
    text_uthmani: "ٱلَّذِينَ",
    code_v2: "ﱜ",
    text_qpc_hafs: "ٱلَّذِينَ",
    line_number: 6,
    location_v2: "1:7:2",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_002.mp3",
  },
  {
    id: 8413,
    text_uthmani: "أَنْعَمْتَ",
    code_v2: "ﱝ",
    text_qpc_hafs: "أَنۡعَمۡتَ",
    line_number: 6,
    location_v2: "1:7:3",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_003.mp3",
  },
  {
    id: 8414,
    text_uthmani: "عَلَيْهِمْ",
    code_v2: "ﱞ",
    text_qpc_hafs: "عَلَيۡهِمۡ",
    line_number: 7,
    location_v2: "1:7:4",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_004.mp3",
  },
  {
    id: 8415,
    text_uthmani: "غَيْرِ",
    code_v2: "ﱟ",
    text_qpc_hafs: "غَيۡرِ",
    line_number: 7,
    location_v2: "1:7:5",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_005.mp3",
  },
  {
    id: 8416,
    text_uthmani: "ٱلْمَغْضُوبِ",
    code_v2: "ﱠ",
    text_qpc_hafs: "ٱلۡمَغۡضُوبِ",
    line_number: 7,
    location_v2: "1:7:6",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_006.mp3",
  },
  {
    id: 8417,
    text_uthmani: "عَلَيْهِمْ",
    code_v2: "ﱡ",
    text_qpc_hafs: "عَلَيۡهِمۡ",
    line_number: 7,
    location_v2: "1:7:7",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_007.mp3",
  },
  {
    id: 8418,
    text_uthmani: "وَلَا",
    code_v2: "ﱢ",
    text_qpc_hafs: "وَلَا",
    line_number: 8,
    location_v2: "1:7:8",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_008.mp3",
  },
  {
    id: 8419,
    text_uthmani: "ٱلضَّآلِّينَ",
    code_v2: "ﱣ",
    text_qpc_hafs: "ٱلضَّآلِّينَ",
    line_number: 8,
    location_v2: "1:7:9",
    verse_key: "1:7",
    char_type_name: "word",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: "wbw/001_007_009.mp3",
  },
  {
    id: 8420,
    text_uthmani: "٧",
    code_v2: "ﱤ",
    text_qpc_hafs: "٧",
    line_number: 8,
    location_v2: "1:7:10",
    verse_key: "1:7",
    char_type_name: "end",
    verse_id: 7,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
  {
    id: 88473,
    text_uthmani: null,
    code_v2: null,
    text_qpc_hafs: null,
    line_number: 1,
    location_v2: "1:1:0",
    verse_key: null,
    char_type_name: "surah",
    verse_id: 0,
    chapter_id: 1,
    page_number: 1,
    audio_url: null,
  },
];
