export const parts = [
  { part: 1, startPage: 1, endPage: 21, title: "الأول" },
  { part: 2, startPage: 22, endPage: 41, title: "الثاني" },
  { part: 3, startPage: 42, endPage: 61, title: "الثالث" },
  { part: 4, startPage: 62, endPage: 81, title: "الرابع" },
  { part: 5, startPage: 82, endPage: 101, title: "الخامس" },
  { part: 6, startPage: 102, endPage: 120, title: "السادس" },
  { part: 7, startPage: 121, endPage: 141, title: "السابع" },
  { part: 8, startPage: 142, endPage: 161, title: "الثامن" },
  { part: 9, startPage: 162, endPage: 181, title: "التاسع" },
  { part: 10, startPage: 182, endPage: 200, title: "العاشر" },
  { part: 11, startPage: 201, endPage: 221, title: "الحادي عشر" },
  { part: 12, startPage: 222, endPage: 241, title: "الثاني عشر" },
  { part: 13, startPage: 242, endPage: 261, title: "الثالث عشر" },
  { part: 14, startPage: 262, endPage: 281, title: "الرابع عشر" },
  { part: 15, startPage: 282, endPage: 301, title: "الخامس عشر" },
  { part: 16, startPage: 302, endPage: 321, title: "السادس عشر" },
  { part: 17, startPage: 322, endPage: 341, title: "السابع عشر" },
  { part: 18, startPage: 342, endPage: 361, title: "الثامن عشر" },
  { part: 19, startPage: 362, endPage: 381, title: "التاسع عشر" },
  { part: 20, startPage: 382, endPage: 401, title: "العشرون" },
  { part: 21, startPage: 402, endPage: 421, title: "الحادي والعشرون" },
  { part: 22, startPage: 422, endPage: 441, title: "الثاني والعشرون" },
  { part: 23, startPage: 442, endPage: 461, title: "الثالث والعشرون" },
  { part: 24, startPage: 462, endPage: 481, title: "الرابع والعشرون" },
  { part: 25, startPage: 482, endPage: 501, title: "الخامس والعشرون" },
  { part: 26, startPage: 502, endPage: 521, title: "السادس والعشرون" },
  { part: 27, startPage: 522, endPage: 541, title: "السابع والعشرون" },
  { part: 28, startPage: 542, endPage: 561, title: "الثامن والعشرون" },
  { part: 29, startPage: 562, endPage: 581, title: "التاسع والعشرون" },
  { part: 30, startPage: 582, endPage: 604, title: "الثلاثون" },
];
export const mushafFirstTenJuz = [
  {
    juzId: 1,
    juzName: "الجزء الأول",
    pageNumber: 1,
    hezbs: [
      {
        hezId: 1,
        hezbName: "الحزب الأول",
        hezbNumber: "1",
        pageNumber: 1,
        quarters: [
          {
            quarterName: "الربع الأول",
            pageNumber: 1,
            start: { surah: "الفاتحة", ayah: 1 },
            end: { surah: "البقرة", ayah: 25 },
          },
          {
            quarterName: "الربع الثاني",
            pageNumber: 5,
            start: { surah: "البقرة", ayah: 26 },
            end: { surah: "البقرة", ayah: 43 },
          },
          {
            quarterName: "الربع الثالث",
            pageNumber: 7,
            start: { surah: "البقرة", ayah: 44 },
            end: { surah: "البقرة", ayah: 59 },
          },
          {
            quarterName: "الربع الرابع",
            pageNumber: 9,
            start: { surah: "البقرة", ayah: 60 },
            end: { surah: "البقرة", ayah: 74 },
          },
        ],
      },
      {
        hezId: 2,
        hezbName: "الحزب الثاني",
        hezbNumber: "2",
        pageNumber: 11,
        quarters: [
          {
            quarterName: "الربع الأول",
            pageNumber: 11,
            start: { surah: "البقرة", ayah: 75 },
            end: { surah: "البقرة", ayah: 91 },
          },
          {
            quarterName: "الربع الثاني",
            pageNumber: 14,
            start: { surah: "البقرة", ayah: 92 },
            end: { surah: "البقرة", ayah: 105 },
          },
          {
            quarterName: "الربع الثالث",
            pageNumber: 17,
            start: { surah: "البقرة", ayah: 106 },
            end: { surah: "البقرة", ayah: 123 },
          },
          {
            quarterName: "الربع الرابع",
            pageNumber: 19,
            start: { surah: "البقرة", ayah: 124 },
            end: { surah: "البقرة", ayah: 141 },
          },
        ],
      },
    ],
  },
  {
    juzId: 2,
    juzName: "الجزء الثاني",
    pageNumber: 22,
    hezbs: [
      {
        hezId: 3,
        hezbName: "الحزب الثالث",
        hezbNumber: "3",
        pageNumber: 22,
        quarters: [
          {
            quarterName: "الربع الأول",
            pageNumber: 22,
            start: { surah: "البقرة", ayah: 142 },
            end: { surah: "البقرة", ayah: 157 },
          },
          {
            quarterName: "الربع الثاني",
            pageNumber: 24,
            start: { surah: "البقرة", ayah: 158 },
            end: { surah: "البقرة", ayah: 176 },
          },
          {
            quarterName: "الربع الثالث",
            pageNumber: 27,
            start: { surah: "البقرة", ayah: 177 },
            end: { surah: "البقرة", ayah: 188 },
          },
          {
            quarterName: "الربع الرابع",
            pageNumber: 29,
            start: { surah: "البقرة", ayah: 189 },
            end: { surah: "البقرة", ayah: 202 },
          },
        ],
      },
      {
        hezId: 4,
        hezbName: "الحزب الرابع",
        hezbNumber: "4",
        pageNumber: 32,
        quarters: [
          { 
            quarterName: "الربع الأول", 
            pageNumber: 32, 
            start: { "surah": "البقرة", "ayah": 203 }, 
            end: { "surah": "البقرة", "ayah": 218 } 
          },
          { 
            quarterName: "الربع الثاني", 
            pageNumber: 34, 
            start: { "surah": "البقرة", "ayah": 219 }, 
            end: { "surah": "البقرة ", "ayah": 232 }
          },
          { 
            quarterName: "الربع الثالث", 
            pageNumber: 37, 
            start: { "surah": " البقرة", "ayah": 233 }, 
            end: { "surah": "البقرة", "ayah": 242 }
          },
          { 
            quarterName: "الربع الرابع", 
            pageNumber: 39, 
            start: { "surah": "البقرة", "ayah": 243 }, 
            end: { "surah": "البقرة", "ayah": 261 }
          }
        ]
        
      },
    ],
  },
  {
    juzId: 3,
    juzName: "الجزء الثالث",
    pageNumber: 42,
    hezbs: [
      {
        hezId: 5,
        hezbName: "الحزب الخامس",
        hezbNumber: "5",
        pageNumber: 42,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 42 , 
            start: { "surah": "البقرة", "ayah": 253 }, 
            end: { "surah": "البقرة", "ayah": 262 } },
          { quarterName: "الربع الثاني", pageNumber: 44  , 
            start: { "surah": "البقرة", "ayah": 263 }, 
            end: { "surah": "البقرة", "ayah": 271 }},
          { quarterName: "الربع الثالث", pageNumber: 46 , 
            start: { "surah": "البقرة", "ayah": 272 }, 
            end: { "surah": "البقرة", "ayah": 282 }},
          { quarterName: "الربع الرابع", pageNumber: 49 , 
            start: { "surah": "البقرة", "ayah": 283 }, 
            end: { "surah": "آل عمران", "ayah": 14 }},
        ],
      },
      {
        hezId: 6,
        hezbName: "الحزب السادس",
        hezbNumber: "6",
        pageNumber: 51,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 51 ,
            start: { surah: "آل عمران", ayah: 15 },
            end: { surah: "آل عمران", ayah: 32 }, },
          { quarterName: "الربع الثاني", pageNumber: 54 ,
            start: { surah: "آل عمران", ayah: 33 },
            end: { surah: "آل عمران", ayah: 51 },},
          { quarterName: "الربع الثالث", pageNumber: 56 ,
            start: { surah: "آل عمران", ayah: 52 },
            end: { surah: "آل عمران", ayah: 74 },},
          { quarterName: "الربع الرابع", pageNumber: 59 ,
            start: { surah: "آل عمران", ayah: 75 },
            end: { surah: "آل عمران", ayah: 92 },},
        ],
      },
    ],
  },
  {
    juzId: 4,
    juzName: "الجزء الرابع",
    pageNumber: 62,
    hezbs: [
      {
        hezId: 7,
        hezbName: "الحزب السابع",
        hezbNumber: "7",
        pageNumber: 62,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 62 ,
            start: { surah: "آل عمران", ayah: 93 },
            end: { surah: "آل عمران", ayah: 112 },},
          { quarterName: "الربع الثاني", pageNumber: 64 ,
            start: { surah: "آل عمران", ayah: 113 },
            end: { surah: "آل عمران", ayah: 132 }, },
          { quarterName: "الربع الثالث", pageNumber: 67,
            start: { surah: "آل عمران", ayah: 133 },
            end: { surah: "آل عمران", ayah: 152 }, },
          { quarterName: "الربع الرابع", pageNumber: 69,
            start: { surah: "آل عمران", ayah: 153 },
            end: { surah: "آل عمران", ayah: 170 }, },
        ],
      },
      {
        hezId: 8,
        hezbName: "الحزب الثامن",
        hezbNumber: "8",

        pageNumber: 72,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 72 ,
            start: { surah: "آل عمران", ayah: 171 },
            end: { surah: "آل عمران", ayah: 185 },},
          { quarterName: "الربع الثاني", pageNumber: 74 ,
            start: { surah: "آل عمران", ayah: 186 },
            end: { surah: " النساء", ayah: 200 }, },
          { quarterName: "الربع الثالث", pageNumber: 77 ,
            start: { surah: "النساء", ayah: 1 },
            end: { surah: "النساء", ayah: 11 },},
          { quarterName: "الربع الرابع", pageNumber: 79 ,
            start: { surah: "النساء", ayah: 12 },
            end: { surah: "النساء", ayah: 23 },},
        ],
      },
    ],
  },
  {
    juzId: 5,
    juzName: "الجزء الخامس",
    pageNumber: 82,
    hezbs: [
      {
        hezId: 9,
        hezbName: "الحزب التاسع",
        hezbNumber: "9",

        pageNumber: 82,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 82 ,
            start: { surah: "النساء", ayah: 24 },
            end: { surah: "النساء", ayah: 35 },},
          { quarterName: "الربع الثاني", pageNumber: 84 ,
            start: { surah: "النساء", ayah: 36 },
            end: { surah: "النساء", ayah: 57 }, },
          { quarterName: "الربع الثالث", pageNumber: 87,
            start: { surah: "النساء", ayah: 58 },
            end: { surah: "النساء", ayah: 73 }, },
          { quarterName: "الربع الرابع", pageNumber: 89 ,
            start: { surah: "النساء", ayah: 74 },
            end: { surah: "النساء", ayah: 87 }, },
        ],
      },
      {
        hezId: 10,
        hezbName: "الحزب العاشر",
        hezbNumber: "10",

        pageNumber: 92,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 92 ,
            start: { surah: "النساء", ayah: 88 },
            end: { surah: "النساء", ayah: 99 },  },
          { quarterName: "الربع الثاني", pageNumber: 94  ,
            start: { surah: "النساء", ayah: 100 },
            end: { surah: "النساء", ayah: 113 }, },
          { quarterName: "الربع الثالث", pageNumber: 97 ,
            start: { surah: "النساء", ayah: 114 },
            end: { surah: "النساء", ayah: 134 },  },
          { quarterName: "الربع الرابع", pageNumber: 100 ,
            start: { surah: "النساء", ayah: 135 },
            end: { surah: "النساء", ayah: 147 },  },
        ],
      },
    ],
  },
  {
    juzId: 6,
    juzName: "الجزء السادس",
    pageNumber: 102,
    hezbs: [
      {
        hezId: 11,
        hezbName: "الحزب الحادي عشر",
        hezbNumber: "11",

        pageNumber: 102,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 102 ,
            start: { surah: "النساء", ayah: 148 },
            end: { surah: "النساء", ayah: 162 }, },
          { quarterName: "الربع الثاني", pageNumber: 104 ,
            start: { surah: "النساء", ayah: 163 },
            end: { surah: "النساء", ayah: 176 }, },
          { quarterName: "الربع الثالث", pageNumber: 106 ,
            start: { surah: "المائدة", ayah: 1 },
            end: { surah: "المائدة", ayah: 11 }, },
          { quarterName: "الربع الرابع", pageNumber: 109 ,
            start: { surah: "المائدة", ayah: 12 },
            end: { surah: "المائدة", ayah: 26 }, },
        ],
      },
      {
        hezId: 12,
        hezbName: "الحزب الثاني عشر",
        hezbNumber: "12",

        pageNumber: 112,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 112,
            start: { surah: "المائدة", ayah: 27 },
            end: { surah: "المائدة", ayah: 40 }, },
          { quarterName: "الربع الثاني", pageNumber: 114,
            start: { surah: "المائدة", ayah: 41 },
            end: { surah: "المائدة", ayah: 50 }, },
          { quarterName: "الربع الثالث", pageNumber: 117,
            start: { surah: "المائدة", ayah: 51 },
            end: { surah: "المائدة", ayah: 66 }, },
          { quarterName: "الربع الرابع", pageNumber: 119,
            start: { surah: "المائدة", ayah: 67 },
            end: { surah: "المائدة", ayah: 81 }, },
        ],
      },
    ],
  },
  {
    juzId: 7,
    juzName: "الجزء السابع",
    pageNumber: 122,
    hezbs: [
      {
        hezId: 13,
        hezbName: "الحزب الثالث عشر",
        hezbNumber: "13",

        pageNumber: 121,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 121 ,
            start: { surah: "المائدة", ayah: 82 },
            end: { surah: "المائدة", ayah: 96 },},
          { quarterName: "الربع الثاني", pageNumber: 142,
            start: { surah: "المائدة", ayah: 97 },
            end: { surah: "المائدة", ayah: 108 }, },
          { quarterName: "الربع الثالث", pageNumber: 126 ,
            start: { surah: "المائدة", ayah: 109 },
            end: { surah: "الانعام", ayah: 12 },},
          { quarterName: "الربع الرابع", pageNumber: 129 ,
            start: { surah: "الانعام", ayah: 13 },
            end: { surah: "الانعام", ayah: 35 },},
        ],
      },
      {
        hezId: 14,
        hezbName: "الحزب الرابع عشر",
        hezbNumber: "14",

        pageNumber: 132,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 132 ,
            start: { surah: "الانعام", ayah: 36 },
            end: { surah: "الانعام", ayah: 58 },},
          { quarterName: "الربع الثاني", pageNumber: 134,
            start: { surah: "الانعام", ayah: 59 },
            end: { surah: "الانعام", ayah: 73 }, },
          { quarterName: "الربع الثالث", pageNumber: 137,
            start: { surah: "الانعام", ayah: 74 },
            end: { surah: "الانعام", ayah: 94 }, },
          { quarterName: "الربع الرابع", pageNumber: 140,
            start: { surah: "الانعام", ayah: 95 },
            end: { surah: "الانعام", ayah: 110 }, },
        ],
      },
    ],
  },
  {
    juzId: 8,
    juzName: "الجزء الثامن",
    pageNumber: 142,
    hezbs: [
      {
        hezId: 15,
        hezbName: "الحزب الخامس عشر",
        hezbNumber: "15",

        pageNumber: 142,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 142,
            start: { surah: "الانعام", ayah: 111 },
            end: { surah: "الانعام", ayah: 126 }, },
          { quarterName: "الربع الثاني", pageNumber: 144,
            start: { surah: "الانعام", ayah: 127 },
            end: { surah: "الانعام", ayah: 140 }, },
          { quarterName: "الربع الثالث", pageNumber: 146,
            start: { surah: "الانعام", ayah: 141 },
            end: { surah: "الانعام", ayah: 150 }, },
          { quarterName: "الربع الرابع", pageNumber: 148,
            start: { surah: "الانعام", ayah: 151 },
            end: { surah: "الانعام", ayah: 165 }, },
        ],
      },
      {
        hezId: 16,
        hezbName: "الحزب السادس عشر",
        hezbNumber: "16",

        pageNumber: 151,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 151,
            start: { surah: "الأعراف", ayah: 1 },
            end: { surah: "الأعراف", ayah: 30 }, },
          { quarterName: "الربع الثاني", pageNumber: 154 ,
            start: { surah: "الأعراف", ayah: 31 },
            end: { surah: "الأعراف", ayah: 46 },},
          { quarterName: "الربع الثالث", pageNumber: 156 ,
            start: { surah: "الأعراف", ayah: 47 },
            end: { surah: "الأعراف", ayah: 64 },},
          { quarterName: "الربع الرابع", pageNumber: 158 ,
            start: { surah: "الأعراف", ayah: 65 },
            end: { surah: "الأعراف", ayah: 87 },},
        ],
      },
    ],
  },
  {
    juzId: 9,
    juzName: "الجزء التاسع",
    pageNumber: 162,
    hezbs: [
      {
        hezId: 17,
        hezbName: "الحزب السابع عشر",
        hezbNumber: "17",

        pageNumber: 162,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 162,
            start: { surah: "الأعراف", ayah: 88 },
            end: { surah: "الأعراف", ayah: 116 }, },
          { quarterName: "الربع الثاني", pageNumber: 164 ,
            start: { surah: "الأعراف", ayah: 117 },
            end: { surah: "الأعراف", ayah: 141 },},
          { quarterName: "الربع الثالث", pageNumber: 167 ,
            start: { surah: "الأعراف", ayah: 142 },
            end: { surah: "الأعراف", ayah: 155 },},
          { quarterName: "الربع الرابع", pageNumber: 170 ,
            start: { surah: "الأعراف", ayah: 156 },
            end: { surah: "الأعراف", ayah: 170 },},
        ],
      },
      {
        hezId: 18,
        hezbName: "الحزب الثامن عشر",
        hezbNumber: "18",

        pageNumber: 173,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 173,
            start: { surah: "الأعراف", ayah: 171 },
            end: { surah: "الأعراف", ayah: 188 }, },
          { quarterName: "الربع الثاني", pageNumber: 175,
            start: { surah: "الأعراف", ayah: 189 },
            end: { surah: "الأعراف", ayah: 206 }, },
          { quarterName: "الربع الثالث", pageNumber: 177,
            start: { surah: "الانفال", ayah: 1 },
            end: { surah: "الانفال", ayah: 21 }, },
          { quarterName: "الربع الرابع", pageNumber: 179,
            start: { surah: "الانفال", ayah: 22 },
            end: { surah: "الانفال", ayah: 40 }, },
        ],
      },
    ],
  },
  {
    juzId: 10,
    juzName: "الجزء العاشر",
    pageNumber: 182,
    hezbs: [
      {
        hezId: 19,
        hezbName: "الحزب التاسع عشر",
        hezbNumber: "19",

        pageNumber: 182,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 182 ,
            start: { surah: "الانفال", ayah: 40 },
            end: { surah: "الانفال", ayah: 60 }, },
          { quarterName: "الربع الثاني", pageNumber: 184 ,
            start: { surah: "الانفال", ayah: 61 },
            end: { surah: "الانفال", ayah: 75 }, },
          { quarterName: "الربع الثالث", pageNumber: 187,
            start: { surah: "التوبة", ayah: 1 },
            end: { surah: "التوبة", ayah: 18 },  },
          { quarterName: "الربع الرابع", pageNumber: 189,
            start: { surah: "التوبة", ayah: 19 },
            end: { surah: "التوبة", ayah: 33 },  },
        ],
      },
      {
        hezId: 20,
        hezbName: "الحزب العشرون",
        hezbNumber: "20",

        pageNumber: 192,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 192,
            start: { surah: "التوبة", ayah: 34 },
            end: { surah: "التوبة", ayah: 45 },  },
          { quarterName: "الربع الثاني", pageNumber: 194,
            start: { surah: "التوبة", ayah: 56 },
            end: { surah: "التوبة", ayah: 59 },  },
          { quarterName: "الربع الثالث", pageNumber: 196,
            start: { surah: "التوبة", ayah: 60 },
            end: { surah: "التوبة", ayah: 74 },  },
          { quarterName: "الربع الرابع", pageNumber: 199,
            start: { surah: "التوبة", ayah: 75 },
            end: { surah: "التوبة", ayah: 92 },  },
        ],
      },
    ],
  },

  {
    juzId: 11,
    juzName: "الجزء الحادي عشر",
    pageNumber: 202,
    hezbs: [
      {
        hezId: 21,
        hezbName: "الحزب الواحد والعشرون",
        hezbNumber: "21",
        pageNumber: 201,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 201,
            start: { surah: "التوبة", ayah: 93 },
            end: { surah: "التوبة", ayah: 110 },  },
          { quarterName: "الربع الثاني", pageNumber: 204 ,
            start: { surah: "التوبة", ayah: 111 },
            end: { surah: "التوبة", ayah: 121 }, },
          { quarterName: "الربع الثالث", pageNumber: 206,
            start: { surah: "التوبة", ayah: 122 },
            end: { surah: "يونس", ayah: 10 },  },
          { quarterName: "الربع الرابع", pageNumber: 209 ,
            start: { surah: "يونس", ayah: 11 },
            end: { surah: "يونس", ayah: 25 }, },
        ],
      },
      {
        hezId: 22,
        hezbName: "الحزب الثاني والعشرون",
        hezbNumber: "22",

        pageNumber: 212,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 212 ,
            start: { surah: "يونس", ayah: 26 },
            end: { surah: "يونس", ayah: 52 }, },
          { quarterName: "الربع الثاني", pageNumber: 214  ,
            start: { surah: "يونس", ayah: 53 },
            end: { surah: "يونس", ayah: 70 },},
          { quarterName: "الربع الثالث", pageNumber: 217  ,
            start: { surah: "يونس", ayah: 71 },
            end: { surah: "يونس", ayah: 89 },},
          { quarterName: "الربع الرابع", pageNumber: 219  ,
            start: { surah: "يونس", ayah: 90 },
            end: { surah: "هود", ayah: 5 },},
        ],
      },
    ],
  },
  {
    juzId: 12,
    juzName: "الجزء الثاني عشر",
    pageNumber: 222,
    hezbs: [
      {
        hezId: 23,
        hezbName: "الحزب الثالث والعشرون",
        hezbNumber: "23",

        pageNumber: 222,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 222  ,
            start: { surah: "هود", ayah: 6 },
            end: { surah: "هود", ayah: 23 },},
          { quarterName: "الربع الثاني", pageNumber: 224  ,
            start: { surah: "هود", ayah: 24 },
            end: { surah: "هود", ayah: 40 },},
          { quarterName: "الربع الثالث", pageNumber: 226  ,
            start: { surah: "هود", ayah: 41 },
            end: { surah: "هود", ayah: 60 },},
          { quarterName: "الربع الرابع", pageNumber: 228 ,
            start: { surah: "هود", ayah: 61 },
            end: { surah: "هود", ayah: 83 }, },
        ],
      },
      {
        hezId: 24,
        hezbName: "الحزب الرابع والعشرون",
        hezbNumber: "24",

        pageNumber: 231,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 231  ,
            start: { surah: "هود", ayah: 84 },
            end: { surah: "هود", ayah: 107 }, },
          { quarterName: "الربع الثاني", pageNumber: 233  ,
            start: { surah: "هود", ayah: 108 },
            end: { surah: "يوسف", ayah: 6 },},
          { quarterName: "الربع الثالث", pageNumber: 236  ,
            start: { surah: "يوسف", ayah: 7 },
            end: { surah: "هود", ayah: 29 },},
          { quarterName: "الربع الرابع", pageNumber: 238  ,
            start: { surah: "يوسف", ayah: 30 },
            end: { surah: "يوسف", ayah: 52 },},
        ],
      },
    ],
  },
  {
    juzId: 13,
    juzName: "الجزء الثالث عشر",
    pageNumber: 242,
    hezbs: [
      {
        hezId: 25,
        hezbName: "الحزب الخامس والعشرون",
        hezbNumber: "25",

        pageNumber: 242,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 242   ,
            start: { surah: "يوسف", ayah: 53 },
            end: { surah: "يوسف", ayah: 76 },},
          { quarterName: "الربع الثاني", pageNumber: 244  ,
            start: { surah: "يوسف", ayah: 77 },
            end: { surah: "يوسف", ayah: 100 }, },
          { quarterName: "الربع الثالث", pageNumber: 247  ,
            start: { surah: "يوسف", ayah: 101 },
            end: { surah: "الرعد", ayah: 4 }, },
          { quarterName: "الربع الرابع", pageNumber: 249  ,
            start: { surah: "الرعد", ayah: 5 },
            end: { surah: "الرعد", ayah: 18 }, },
        ],
      },
      {
        hezId: 26,
        hezbName: "الحزب السادس والعشرون",
        hezbNumber: "26",

        pageNumber: 252,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 252   ,
            start: { surah: "يوسف", ayah: 19 },
            end: { surah: "يوسف", ayah: 34 },},
          { quarterName: "الربع الثاني", pageNumber: 254  ,
            start: { surah: "يوسف", ayah: 35 },
            end: { surah: "ابراهيم", ayah: 9 }, },
          { quarterName: "الربع الثالث", pageNumber: 256  ,
            start: { surah: "ابراهيم", ayah: 10 },
            end: { surah: "ابراهيم", ayah: 27 }, },
          { quarterName: "الربع الرابع", pageNumber: 259  ,
            start: { surah: "ابراهيم", ayah: 28 },
            end: { surah: "ابراهيم", ayah: 52 }, },
        ],
      },
    ],
  },
  {
    juzId: 14,
    juzName: "الجزء الرابع عشر",
    pageNumber: 262,
    hezbs: [
      {
        hezId: 27,
        hezbName: "الحزب السابع والعشرون",
        hezbNumber: "27",

        pageNumber: 262,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 262   ,
            start: { surah: "الحجر", ayah: 1 },
            end: { surah: "الحجر", ayah: 48 },},
          { quarterName: "الربع الثاني", pageNumber: 264  ,
            start: { surah: "الحجر", ayah: 49 },
            end: { surah: "الحجر", ayah: 99 }, },
          { quarterName: "الربع الثالث", pageNumber: 267  ,
            start: { surah: "النحل", ayah: 1 },
            end: { surah: "النحل", ayah: 29 }, },
          { quarterName: "الربع الرابع", pageNumber: 270  ,
            start: { surah: "النحل", ayah: 30 },
            end: { surah: "النحل", ayah: 50 }, },
        ],
      },
      {
        hezId: 28,
        hezbName: "الحزب الثامن والعشرون",
        hezbNumber: "28",

        pageNumber: 272,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 272   ,
            start: { surah: "النحل", ayah: 51 },
            end: { surah: "النحل", ayah: 74 },},
          { quarterName: "الربع الثاني", pageNumber: 275  ,
            start: { surah: "النحل", ayah: 75 },
            end: { surah: "النحل", ayah: 89 }, },
          { quarterName: "الربع الثالث", pageNumber: 277  ,
            start: { surah: "النحل", ayah: 90 },
            end: { surah: "النحل", ayah: 110 }, },
          { quarterName: "الربع الرابع", pageNumber: 280  ,
            start: { surah: "النحل", ayah: 111 },
            end: { surah: "الرعد", ayah: 128 }, },
        ],
      },
    ],
  },
  {
    juzId: 15,
    juzName: "الجزء الخامس عشر",
    pageNumber: 282,
    hezbs: [
      {
        hezId: 29,
        hezbName: "الحزب التاسع والعشرون",
        hezbNumber: "29",

        pageNumber: 282,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 282   ,
            start: { surah: "الاسراء", ayah: 1 },
            end: { surah: "الاسراء", ayah: 22 },},
          { quarterName: "الربع الثاني", pageNumber: 284  ,
            start: { surah: "الاسراء", ayah: 23 },
            end: { surah: "الاسراء", ayah: 49 }, },
          { quarterName: "الربع الثالث", pageNumber: 287  ,
            start: { surah: "الاسراء", ayah: 50 },
            end: { surah: "الاسراء", ayah: 69 }, },
          { quarterName: "الربع الرابع", pageNumber: 289  ,
            start: { surah: "الاسراء", ayah: 70 },
            end: { surah: "الاسراء", ayah: 98 }, },
        ],
      },
      {
        hezId: 30,
        hezbName: "الحزب الثلاثون",
        hezbNumber: "30",

        pageNumber: 292,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 292   ,
            start: { surah: "الاسراء", ayah: 99 },
            end: { surah: "الكهف", ayah: 16 },},
          { quarterName: "الربع الثاني", pageNumber: 295  ,
            start: { surah: "الكهف", ayah: 17 },
            end: { surah: "الكهف", ayah: 31 }, },
          { quarterName: "الربع الثالث", pageNumber: 297  ,
            start: { surah: "الكهف", ayah: 32 },
            end: { surah: "الكهف", ayah: 50 }, },
          { quarterName: "الربع الرابع", pageNumber: 299  ,
            start: { surah: "الكهف", ayah: 51 },
            end: { surah: "الكهف", ayah: 74 }, },
        ],
      },
    ],
  },
  {
    juzId: 16,
    juzName: "الجزء السادس عشر",
    pageNumber: 302,
    hezbs: [
      {
        hezId: 31,
        hezbName: "الحزب الواحد والثلاثون",
        hezbNumber: "31",

        pageNumber: 302,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 302  ,
            start: { surah: "الكهف", ayah: 75 },
            end: { surah: "الكهف", ayah: 98 },},
          { quarterName: "الربع الثاني", pageNumber: 304  ,
            start: { surah: "الكهف", ayah: 99 },
            end: { surah: "مريم", ayah: 21 }, },
          { quarterName: "الربع الثالث", pageNumber: 306  ,
            start: { surah: "مريم", ayah: 22 },
            end: { surah: "مريم", ayah: 58}, },
          { quarterName: "الربع الرابع", pageNumber: 309  ,
            start: { surah: "مريم", ayah: 59 },
            end: { surah: "مريم", ayah: 98 }, },
        ],
      },
      {
        hezId: 32,
        hezbName: "الحزب الثاني والثلاثون",
        hezbNumber: "32",

        pageNumber: 312,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 312   ,
            start: { surah: "طه", ayah: 1 },
            end: { surah: "طه", ayah: 54},},
          { quarterName: "الربع الثاني", pageNumber: 315  ,
            start: { surah: "طه", ayah: 55 },
            end: { surah: "طه", ayah: 82 }, },
          { quarterName: "الربع الثالث", pageNumber: 317  ,
            start: { surah: "طه", ayah: 83},
            end: { surah: "طه", ayah: 110 }, },
          { quarterName: "الربع الرابع", pageNumber: 319  ,
            start: { surah: "طه", ayah: 111 },
            end: { surah: "طه", ayah: 135 }, },
        ],
      },
    ],
  },
  {
    juzId: 17,
    juzName: "الجزء السابع عشر",
    pageNumber: 322,
    hezbs: [
      {
        hezId: 33,
        hezbName: "الحزب الثالث والثلاثون",
        hezbNumber: "33",

        pageNumber: 322,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 322   ,
            start: { surah: "الانبياء", ayah: 1 },
            end: { surah: "الانبياء ", ayah: 28 },},
          { quarterName: "الربع الثاني", pageNumber: 324  ,
            start: { surah: "الانبياء", ayah: 29 },
            end: { surah: "الانبياء", ayah: 50 }, },
          { quarterName: "الربع الثالث", pageNumber: 326  ,
            start: { surah: "الانبياء", ayah: 51 },
            end: { surah: "الانبياء", ayah: 82 }, },
          { quarterName: "الربع الرابع", pageNumber: 329  ,
            start: { surah: "الانبياء", ayah: 83 },
            end: { surah: "الانبياء", ayah: 112 }, },
        ],
      },
      {
        hezId: 34,
        hezbName: "الحزب الرابع والثلاثون",
        hezbNumber: "34",

        pageNumber: 332,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 332   ,
            start: { surah: "الحج", ayah: 1 },
            end: { surah: "الحج", ayah: 18 },},
          { quarterName: "الربع الثاني", pageNumber: 334  ,
            start: { surah: "الحج", ayah: 19 },
            end: { surah: "الحج", ayah: 37 }, },
          { quarterName: "الربع الثالث", pageNumber: 336  ,
            start: { surah: "الحج", ayah: 38 },
            end: { surah: "الحج", ayah: 59 }, },
          { quarterName: "الربع الرابع", pageNumber: 339  ,
            start: { surah: "الحج", ayah: 60 },
            end: { surah: "الحج", ayah: 78 }, },
        ],
      },
    ],
  },
  {
    juzId: 18,
    juzName: "الجزء الثامن عشر",
    pageNumber: 342,
    hezbs: [
      {
        hezId: 35,
        hezbName: "الحزب الخامس والثلاثون",
        hezbNumber: "35",

        pageNumber: 342,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 342   ,
            start: { surah: "المؤمنون", ayah: 1 },
            end: { surah: "المؤمنون", ayah: 35 },},
          { quarterName: "الربع الثاني", pageNumber: 344  ,
            start: { surah: "المؤمنون", ayah: 36 },
            end: { surah: "المؤمنون", ayah: 74 }, },
          { quarterName: "الربع الثالث", pageNumber: 347  ,
            start: { surah: "المؤمنون", ayah:75 },
            end: { surah: "المؤمنون", ayah: 118}, },
          { quarterName: "الربع الرابع", pageNumber: 350  ,
            start: { surah: "النور", ayah: 1 },
            end: { surah: "النور", ayah: 20 }, },
        ],
      },
      {
        hezId: 36,
        hezbName: "الحزب السادس والثلاثون",
        hezbNumber: "36",

        pageNumber: 352,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 452   ,
            start: { surah: "النور", ayah: 21 },
            end: { surah: "النور", ayah: 34 },},
          { quarterName: "الربع الثاني", pageNumber: 354  ,
            start: { surah: "النور", ayah: 35 },
            end: { surah: "النور", ayah: 52 }, },
          { quarterName: "الربع الثالث", pageNumber: 356  ,
            start: { surah: "النور", ayah: 53 },
            end: { surah: "النور", ayah: 64 }, },
          { quarterName: "الربع الرابع", pageNumber: 359  ,
            start: { surah: "الفرقان", ayah: 1 },
            end: { surah: "الفرقان", ayah: 20 }, },
        ],
      },
    ],
  },
  {
    juzId: 19,
    juzName: "الجزء التاسع عشر",
    pageNumber: 362,
    hezbs: [
      {
        hezId: 37,
        hezbName: "الحزب السابع والثلاثون",
        hezbNumber: "37",

        pageNumber: 362,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 362   ,
            start: { surah: "الفرقان", ayah: 21 },
            end: { surah: "الفرقان", ayah: 52 },},
          { quarterName: "الربع الثاني", pageNumber: 364  ,
            start: { surah: "الفرقان", ayah: 53 },
            end: { surah: "الفرقان", ayah: 77 }, },
          { quarterName: "الربع الثالث", pageNumber: 367  ,
            start: { surah: "الشعراء", ayah: 1 },
            end: { surah: "الشعراء", ayah: 51 }, },
          { quarterName: "الربع الرابع", pageNumber: 369  ,
            start: { surah: "الشعراء", ayah: 52 },
            end: { surah: "الشعراء", ayah: 110 }, },
        ],
      },
      {
        hezId: 38,
        hezbName: "الحزب الثامن والثلاثون",
        hezbNumber: "38",

        pageNumber: 371,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 371   ,
            start: { surah: "الشعراء", ayah:111 },
            end: { surah: "الشعراء", ayah: 180 },},
          { quarterName: "الربع الثاني", pageNumber: 374  ,
            start: { surah: "الشعراء", ayah: 181 },
            end: { surah: "الشعراء", ayah: 227 }, },
          { quarterName: "الربع الثالث", pageNumber: 377  ,
            start: { surah: "النمل", ayah: 1 },
            end: { surah: "النمل", ayah: 26 }, },
          { quarterName: "الربع الرابع", pageNumber: 379  ,
            start: { surah: "النمل", ayah: 27 },
            end: { surah: "النمل", ayah: 55 }, },
        ],
      },
    ],
  },
  {
    juzId: 20,
    juzName: "الجزء العشرون",
    pageNumber: 382,
    hezbs: [
      {
        hezId: 39,
        hezbName: "الحزب التاسع والثلاثون",
        hezbNumber: "39",

        pageNumber: 382,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 382   ,
            start: { surah: "النمل", ayah: 56 },
            end: { surah: "النمل", ayah: 81 },},
          { quarterName: "الربع الثاني", pageNumber: 384  ,
            start: { surah: "النمل", ayah: 82 },
            end: { surah: "القصص", ayah: 11 }, },
          { quarterName: "الربع الثالث", pageNumber: 386  ,
            start: { surah: "القصص", ayah: 12 },
            end: { surah: "القصص", ayah: 28 }, },
          { quarterName: "الربع الرابع", pageNumber: 389  ,
            start: { surah: "القصص", ayah: 29 },
            end: { surah: "القصص", ayah: 50 }, },
        ],
      },
      {
        hezId: 40,
        hezbName: "الحزب الأربعون",
        hezbNumber: "40",

        pageNumber: 392,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 392   ,
            start: { surah: "القصص", ayah: 51 },
            end: { surah: "القصص", ayah: 75 },},
          { quarterName: "الربع الثاني", pageNumber: 394  ,
            start: { surah: "القصص", ayah: 76 },
            end: { surah: "القصص", ayah: 88 }, },
          { quarterName: "الربع الثالث", pageNumber: 396  ,
            start: { surah: "العنكبوت", ayah: 1 },
            end: { surah: "العنكبوت", ayah: 25 }, },
          { quarterName: "الربع الرابع", pageNumber: 399  ,
            start: { surah: "العنكبوت", ayah: 26 },
            end: { surah: "العنكبوت", ayah: 45 }, },
        ],
      },
    ],
  },

  {
    juzId: 21,
    juzName: "الجزء الواحد والعشرون",
    pageNumber: 402,
    hezbs: [
      {
        hezId: 41,
        hezbName: "الحزب الواحد والأربعون",
        hezbNumber: "41",

        pageNumber: 402,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 402   ,
            start: { surah: "العنكبوت", ayah: 46 },
            end: { surah: "العنكبوت", ayah: 69 },},
          { quarterName: "الربع الثاني", pageNumber: 404  ,
            start: { surah: "الروم", ayah: 1 },
            end: { surah: "الروم", ayah: 30 }, },
          { quarterName: "الربع الثالث", pageNumber: 407  ,
            start: { surah: "الروم", ayah: 31 },
            end: { surah: "الروم", ayah: 53 }, },
          { quarterName: "الربع الرابع", pageNumber: 410  ,
            start: { surah: "الروم", ayah: 54 },
            end: { surah: "لقمان", ayah: 21 }, },
        ],
      },
      {
        hezId: 42,
        hezbName: "الحزب الثاني والأربعون",
        hezbNumber: "42",

        pageNumber: 413,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 414   ,
            start: { surah: "لقمان", ayah: 22 },
            end: { surah: "السجدة", ayah: 10 },},
          { quarterName: "الربع الثاني", pageNumber: 415  ,
            start: { surah: "السجدة", ayah: 11 },
            end: { surah: "السجدة", ayah: 30 }, },
          { quarterName: "الربع الثالث", pageNumber: 418  ,
            start: { surah: "الاحزاب", ayah: 1 },
            end: { surah: "الاحزاب", ayah: 17}, },
          { quarterName: "الربع الرابع", pageNumber: 420  ,
            start: { surah: "الاحزاب", ayah: 18 },
            end: { surah: "الاحزاب", ayah: 30 }, },
        ],
      },
    ],
  },
  {
    juzId: 22,
    juzName: "الجزء الثاني والعشرون",
    pageNumber: 422,
    hezbs: [
      {
        hezId: 43,
        hezbName: "الحزب الثالث والأربعون",
        hezbNumber: "43",

        pageNumber: 422,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 422   ,
            start: { surah: "الاحزاب", ayah: 31 },
            end: { surah: "الاحزاب", ayah: 50 },},
          { quarterName: "الربع الثاني", pageNumber: 425  ,
            start: { surah: "الاحزاب", ayah: 51 },
            end: { surah: "الاحزاب", ayah: 59 }, },
          { quarterName: "الربع الثالث", pageNumber: 426  ,
            start: { surah: "الاحزاب", ayah: 60 },
            end: { surah: "سبأ", ayah: 9 }, },
          { quarterName: "الربع الرابع", pageNumber: 429  ,
            start: { surah: "سبأ", ayah: 10 },
            end: { surah: "سبأ", ayah: 23 }, },
        ],
      },
      {
        hezId: 44,
        hezbName: "الحزب الرابع والأربعون",
        hezbNumber: "44",

        pageNumber: 431,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 431   ,
            start: { surah: "سبأ", ayah: 24 },
            end: { surah: "سبأ", ayah: 45 },},
          { quarterName: "الربع الثاني", pageNumber: 433  ,
            start: { surah: "سبأ", ayah: 46 },
            end: { surah: "فاطر", ayah: 14 }, },
          { quarterName: "الربع الثالث", pageNumber: 436  ,
            start: { surah: "فاطر", ayah: 15 },
            end: { surah: "فاطر", ayah: 40 }, },
          { quarterName: "الربع الرابع", pageNumber: 439  ,
            start: { surah: "فاطر", ayah: 41 },
            end: { surah: "يس", ayah: 27 }, },
        ],
      },
    ],
  },
  {
    juzId: 23,
    juzName: "الجزء الثالث والعشرون",
    pageNumber: 442,
    hezbs: [
      {
        hezId: 45,
        hezbName: "الحزب الخامس والأربعون",
        hezbNumber: "45",

        pageNumber: 442,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 442   ,
            start: { surah: "فاطر", ayah: 28 },
            end: { surah: "فاطر", ayah: 59 },},
          { quarterName: "الربع الثاني", pageNumber: 444  ,
            start: { surah: "فاطر", ayah: 60 },
            end: { surah: "الصافات", ayah: 21 }, },
          { quarterName: "الربع الثالث", pageNumber: 446  ,
            start: { surah: "الصافات", ayah: 22 },
            end: { surah: "الصافات", ayah: 82 }, },
          { quarterName: "الربع الرابع", pageNumber: 649  ,
            start: { surah: "الصافات", ayah: 83 },
            end: { surah: "الصافات", ayah: 144 }, },
        ],
      },
      {
        hezId: 46,
        hezbName: "الحزب السادس والأربعون",
        hezbNumber: "46",

        pageNumber: 451,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 451   ,
            start: { surah: "الصافات", ayah: 145 },
            end: { surah: "ص", ayah: 20 },},
          { quarterName: "الربع الثاني", pageNumber: 454  ,
            start: { surah: "ص", ayah: 21 },
            end: { surah: "ص", ayah: 51 }, },
          { quarterName: "الربع الثالث", pageNumber: 456  ,
            start: { surah: "ص", ayah: 52 },
            end: { surah: "الزمر", ayah: 7 }, },
          { quarterName: "الربع الرابع", pageNumber: 459  ,
            start: { surah: "الزمر", ayah: 8},
            end: { surah: "الزمر", ayah: 31 }, },
        ],
      },
    ],
  },
  {
    juzId: 24,
    juzName: "الجزء الرابع والعشرون",
    pageNumber: 462,
    hezbs: [
      {
        hezId: 47,
        hezbName: "الحزب السابع والأربعون",
        hezbNumber: "47",

        pageNumber: 462,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 462   ,
            start: { surah: "الزمر", ayah: 32 },
            end: { surah: "الزمر", ayah: 52 },},
          { quarterName: "الربع الثاني", pageNumber: 464  ,
            start: { surah: "الزمر", ayah: 53 },
            end: { surah: "الزمر", ayah: 75 }, },
          { quarterName: "الربع الثالث", pageNumber: 467  ,
            start: { surah: "غافر", ayah: 1 },
            end: { surah: "غافر", ayah: 20 }, },
          { quarterName: "الربع الرابع", pageNumber: 469  ,
            start: { surah: "غافر", ayah: 21 },
            end: { surah: "غافر", ayah: 40 }, },
        ],
      },
      {
        hezId: 48,
        hezbName: "الحزب الثامن والأربعون",
        hezbNumber: "48",

        pageNumber: 472,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 472   ,
            start: { surah: "غافر", ayah: 41 },
            end: { surah: "غافر", ayah: 65 },},
          { quarterName: "الربع الثاني", pageNumber: 474  ,
            start: { surah: "غافر", ayah: 66 },
            end: { surah: "فصلت", ayah: 8 }, },
          { quarterName: "الربع الثالث", pageNumber: 477  ,
            start: { surah: "فصلت", ayah: 9 },
            end: { surah: "فصلت", ayah: 24 }, },
          { quarterName: "الربع الرابع", pageNumber: 479  ,
            start: { surah: "فصلت", ayah: 25 },
            end: { surah: "فصلت", ayah: 46 }, },
        ],
      },
    ],
  },
  {
    juzId: 25,
    juzName: "الجزء الخامس والعشرون",
    pageNumber: 482,
    hezbs: [
      {
        hezId: 49,
        hezbName: "الحزب التاسع والأربعون",
        hezbNumber: "49",

        pageNumber: 482,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 482   ,
            start: { surah: "الشورى", ayah: 47 },
            end: { surah: "الشورى", ayah: 12 },},
          { quarterName: "الربع الثاني", pageNumber: 484  ,
            start: { surah: "الشورى", ayah: 13 },
            end: { surah: "الشورى", ayah:26 }, },
          { quarterName: "الربع الثالث", pageNumber: 486  ,
            start: { surah: "الشورى", ayah: 27 },
            end: { surah: "الشورى", ayah: 50 }, },
          { quarterName: "الربع الرابع", pageNumber: 488  ,
            start: { surah: "الشورى", ayah: 51},
            end: { surah: "الزخرف", ayah: 23 }, },
        ],
      },
      {
        hezId: 50,
        hezbName: "الحزب الخمسون",
        hezbNumber: "50",

        pageNumber: 491,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 491   ,
            start: { surah: "الزخرف", ayah: 24 },
            end: { surah: "الزخرف", ayah: 56 },},
          { quarterName: "الربع الثاني", pageNumber: 493  ,
            start: { surah: "الزخرف", ayah: 57 },
            end: { surah: "الدخان", ayah: 16 }, },
          { quarterName: "الربع الثالث", pageNumber: 496  ,
            start: { surah: "الدخان", ayah: 17 },
            end: { surah: "الجاثية", ayah: 11}, },
          { quarterName: "الربع الرابع", pageNumber: 499  ,
            start: { surah: "الجاثية", ayah: 12 },
            end: { surah: "الجاثية", ayah: 37 }, },
        ],
      },
    ],
  },
  {
    juzId: 26,
    juzName: "الجزء السادس والعشرون",
    pageNumber: 502,
    hezbs: [
      {
        hezId: 51,
        hezbName: "الحزب الحادي والخمسون",
        hezbNumber: "51",

        pageNumber: 502,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 502   ,
            start: { surah: "الاحقاف", ayah: 1 },
            end: { surah: "الاحقاف", ayah: 20 },},
          { quarterName: "الربع الثاني", pageNumber: 505  ,
            start: { surah: "الاحقاف", ayah: 21 },
            end: { surah: "محمد", ayah: 9 }, },
          { quarterName: "الربع الثالث", pageNumber: 507  ,
            start: { surah: "محمد", ayah: 10 },
            end: { surah: "محمد", ayah: 32 }, },
          { quarterName: "الربع الرابع", pageNumber: 510  ,
            start: { surah: "محمد", ayah: 33 },
            end: { surah: "الفتح", ayah: 18 }, },
        ],
      },
      {
        hezId: 52,
        hezbName: "الحزب الثاني والخمسون",
        hezbNumber: "52",

        pageNumber: 513,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 513   ,
            start: { surah: "الفتح", ayah: 18 },
            end: { surah: "الفتح", ayah: 29 },},
          { quarterName: "الربع الثاني", pageNumber: 515  ,
            start: { surah: "الحجرات", ayah: 1 },
            end: { surah: "الحجرات", ayah: 13 }, },
          { quarterName: "الربع الثالث", pageNumber: 517  ,
            start: { surah: "الحجرات", ayah: 14 },
            end: { surah: "ق", ayah: 26 }, },
          { quarterName: "الربع الرابع", pageNumber: 519  ,
            start: { surah: "ق", ayah: 27 },
            end: { surah: "الذاريات", ayah: 30 }, },
        ],
      },
    ],
  },
  {
    juzId: 27,
    juzName: "الجزء السابع والعشرون",
    pageNumber: 522,
    hezbs: [
      {
        hezId: 53,
        hezbName: "الحزب الثالث والخمسون",
        hezbNumber: "53",

        pageNumber: 522,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 522   ,
            start: { surah: "الذاريات", ayah: 31 },
            end: { surah: "الطور", ayah: 23 },},
          { quarterName: "الربع الثاني", pageNumber: 524  ,
            start: { surah: "الطور", ayah: 24 },
            end: { surah: "النجم", ayah: 25 }, },
          { quarterName: "الربع الثالث", pageNumber: 526  ,
            start: { surah: "النحم", ayah: 26 },
            end: { surah: "القمر", ayah: 8 }, },
          { quarterName: "الربع الرابع", pageNumber: 529  ,
            start: { surah: "القمر", ayah: 9 },
            end: { surah: "القمر", ayah: 55 }, },
        ],
      },
      {
        hezId: 54,
        hezbName: "الحزب الرابع والخمسون",
        hezbNumber: "54",

        pageNumber: 531,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 531   ,
            start: { surah: "الرحمن", ayah: 1 },
            end: { surah: "الرحمن", ayah: 78 },},
          { quarterName: "الربع الثاني", pageNumber: 534  ,
            start: { surah: "الواقعة", ayah: 1 },
            end: { surah: "الواقعة", ayah: 74 }, },
          { quarterName: "الربع الثالث", pageNumber: 536  ,
            start: { surah: "الواقعة", ayah: 75 },
            end: { surah: "الحديد", ayah: 15 }, },
          { quarterName: "الربع الرابع", pageNumber: 539  ,
            start: { surah: "الحديد", ayah: 16 },
            end: { surah: "الحديد", ayah: 29 }, },
        ],
      },
    ],
  },
  {
    juzId: 28,
    juzName: "الجزء الثامن والعشرون",
    pageNumber: 542,
    hezbs: [
      {
        hezId: 55,
        hezbName: "الحزب الخامس والخمسون",
        hezbNumber: "55",

        pageNumber: 542,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 542   ,
            start: { surah: "المجادلة", ayah: 1 },
            end: { surah: "المجادلة", ayah: 13 },},
          { quarterName: "الربع الثاني", pageNumber: 544  ,
            start: { surah: "المجادلة", ayah: 14 },
            end: { surah: "الحشر", ayah: 10 }, },
          { quarterName: "الربع الثالث", pageNumber: 547  ,
            start: { surah: "الحشر", ayah: 11 },
            end: { surah: "الممتحنة", ayah: 6 }, },
          { quarterName: "الربع الرابع", pageNumber: 550  ,
            start: { surah: "الممتحنة", ayah: 7 },
            end: { surah: "الصف", ayah: 14 }, },
        ],
      },
      {
        hezId: 56,
        hezbName: "الحزب السادس والخمسون",
        hezbNumber: "56",

        pageNumber: 522,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 553   ,
            start: { surah: "الجمعة", ayah: 1 },
            end: { surah: "المافقون", ayah: 3 },},
          { quarterName: "الربع الثاني", pageNumber: 554  ,
            start: { surah: "المنافقون", ayah: 4 },
            end: { surah: "التغابن", ayah: 18 }, },
          { quarterName: "الربع الثالث", pageNumber: 558  ,
            start: { surah: "الطلاق", ayah: 1 },
            end: { surah: "الطلاق", ayah: 12 }, },
          { quarterName: "الربع الرابع", pageNumber: 560  ,
            start: { surah: "التحريم", ayah: 1 },
            end: { surah: "التحريم", ayah: 12 }, },
        ],
      },
    ],
  },
  {
    juzId: 29,
    juzName: "الجزء التاسع والعشرون",
    pageNumber: 562,
    hezbs: [
      {
        hezId: 57,
        hezbName: "الحزب السابع والخمسون",
        hezbNumber: "57",

        pageNumber: 562,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 562   ,
            start: { surah: "الملك", ayah: 1 },
            end: { surah: "الملك", ayah: 30 },},
          { quarterName: "الربع الثاني", pageNumber: 564  ,
            start: { surah: "القلم", ayah: 1 },
            end: { surah: "القلم", ayah: 52 }, },
          { quarterName: "الربع الثالث", pageNumber: 566  ,
            start: { surah: "الحاقة", ayah: 1 },
            end: { surah: "المعارج", ayah: 18 }, },
          { quarterName: "الربع الرابع", pageNumber: 569  ,
            start: { surah: "المعارج", ayah: 19 },
            end: { surah: "نوح", ayah: 28 }, },
        ],
      },
      {
        hezId: 58,
        hezbName: "الحزب الثامن والخمسون",
        hezbNumber: "58",

        pageNumber: 572,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 572   ,
            start: { surah: "الجن", ayah: 1 },
            end: { surah: "المزمل", ayah: 19 }, 
          },
          { quarterName: "الربع الثاني", pageNumber: 575  ,
            start: { surah: "المزمل", ayah: 20 },
            end: { surah: "المدثر", ayah: 56 }, },
          { quarterName: "الربع الثالث", pageNumber: 577  ,
            start: { surah: "القيامة", ayah: 1 },
            end: { surah: "الانسان", ayah: 18 }, },
          { quarterName: "الربع الرابع", pageNumber: 579  ,
            start: { surah: "الانسان", ayah: 19 },
            end: { surah: "المرسلات", ayah: 50 }, },
        ],
      },
    ],
  },
  {
    juzId: 30,
    juzName: "الجزء الثلاثون",
    pageNumber: 582,
    hezbs: [
      {
        hezId: 59,
        hezbName: "الحزب التاسع والخمسون",
        hezbNumber: "59",

        pageNumber: 582,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 582   ,
            start: { surah: "النبأ", ayah: 1 },
            end: { surah: "النازعات", ayah: 46 },},
          { quarterName: "الربع الثاني", pageNumber: 585  ,
            start: { surah: "عبس", ayah: 1 },
            end: { surah: "التكوير", ayah: 29 }, },
          { quarterName: "الربع الثالث", pageNumber: 587  ,
            start: { surah: "الانفطار", ayah: 1 },
            end: { surah: "المطففين", ayah: 46 }, },
          { quarterName: "الربع الرابع", pageNumber: 589  ,
            start: { surah: "الانشقاق", ayah: 1 },
            end: { surah: "الطارق", ayah: 17 }, },
        ],
      },
      {
        hezId: 60,
        hezbName: "الحزب الستون",
        hezbNumber: "60",

        pageNumber: 591,
        quarters: [
          { quarterName: "الربع الأول", pageNumber: 591   ,
            start: { surah: "الاعلى", ayah: 1 },
            end: { surah: "الفجر", ayah: 30 },},
          { quarterName: "الربع الثاني", pageNumber: 594  ,
            start: { surah: "البلد", ayah: 1 },
            end: { surah: "الضحى", ayah: 11 }, },
          { quarterName: "الربع الثالث", pageNumber: 596  ,
            start: { surah: "الشرح", ayah: 1 },
            end: { surah: "العاديات", ayah: 11 }, },
          { quarterName: "الربع الرابع", pageNumber: 600  ,
            start: { surah: "القارعة", ayah: 1 },
            end: { surah: "الناس", ayah: 6 }, },
        ],
      },
    ],
  },
];