export const surahsData = [
  {
    id: 1,
    revelation_place: "makkah",
    name_arabic: "الفاتحة",
    start_page: 1,
    end_page: 1,
    verses_count: 7,
  },
  {
    id: 2,
    revelation_place: "madinah",
    name_arabic: "البقرة",
    start_page: 2,
    end_page: 49,
    verses_count: 286,
  },
  {
    id: 3,
    revelation_place: "madinah",
    name_arabic: "آل عمران",
    start_page: 50,
    end_page: 76,
    verses_count: 200,
  },
  {
    id: 4,
    revelation_place: "madinah",
    name_arabic: "النساء",
    start_page: 77,
    end_page: 106,
    verses_count: 176,
  },
  {
    id: 5,
    revelation_place: "madinah",
    name_arabic: "المائدة",
    start_page: 106,
    end_page: 127,
    verses_count: 120,
  },
  {
    id: 6,
    revelation_place: "makkah",
    name_arabic: "الأنعام",
    start_page: 128,
    end_page: 150,
    verses_count: 165,
  },
  {
    id: 7,
    revelation_place: "makkah",
    name_arabic: "الأعراف",
    start_page: 151,
    end_page: 176,
    verses_count: 206,
  },
  {
    id: 8,
    revelation_place: "madinah",
    name_arabic: "الأنفال",
    start_page: 177,
    end_page: 186,
    verses_count: 75,
  },
  {
    id: 9,
    revelation_place: "madinah",
    name_arabic: "التوبة",
    start_page: 187,
    end_page: 207,
    verses_count: 129,
  },
  {
    id: 10,
    revelation_place: "makkah",
    name_arabic: "يونس",
    start_page: 208,
    end_page: 221,
    verses_count: 109,
  },
  {
    id: 11,
    revelation_place: "makkah",
    name_arabic: "هود",
    start_page: 221,
    end_page: 235,
    verses_count: 123,
  },
  {
    id: 12,
    revelation_place: "makkah",
    name_arabic: "يوسف",
    start_page: 235,
    end_page: 248,
    verses_count: 111,
  },
  {
    id: 13,
    revelation_place: "madinah",
    name_arabic: "الرعد",
    start_page: 249,
    end_page: 255,
    verses_count: 43,
  },
  {
    id: 14,
    revelation_place: "makkah",
    name_arabic: "ابراهيم",
    start_page: 255,
    end_page: 261,
    verses_count: 52,
  },
  {
    id: 15,
    revelation_place: "makkah",
    name_arabic: "الحجر",
    start_page: 262,
    end_page: 267,
    verses_count: 99,
  },
  {
    id: 16,
    revelation_place: "makkah",
    name_arabic: "النحل",
    start_page: 267,
    end_page: 281,
    verses_count: 128,
  },
  {
    id: 17,
    revelation_place: "makkah",
    name_arabic: "الإسراء",
    start_page: 282,
    end_page: 293,
    verses_count: 111,
  },
  {
    id: 18,
    revelation_place: "makkah",
    name_arabic: "الكهف",
    start_page: 293,
    end_page: 304,
    verses_count: 110,
  },
  {
    id: 19,
    revelation_place: "makkah",
    name_arabic: "مريم",
    start_page: 305,
    end_page: 312,
    verses_count: 98,
  },
  {
    id: 20,
    revelation_place: "makkah",
    name_arabic: "طه",
    start_page: 312,
    end_page: 321,
    verses_count: 135,
  },
  {
    id: 21,
    revelation_place: "makkah",
    name_arabic: "الأنبياء",
    start_page: 322,
    end_page: 331,
    verses_count: 112,
  },
  {
    id: 22,
    revelation_place: "madinah",
    name_arabic: "الحج",
    start_page: 332,
    end_page: 341,
    verses_count: 78,
  },
  {
    id: 23,
    revelation_place: "makkah",
    name_arabic: "المؤمنون",
    start_page: 342,
    end_page: 349,
    verses_count: 118,
  },
  {
    id: 24,
    revelation_place: "madinah",
    name_arabic: "النور",
    start_page: 350,
    end_page: 359,
    verses_count: 64,
  },
  {
    id: 25,
    revelation_place: "makkah",
    name_arabic: "الفرقان",
    start_page: 359,
    end_page: 366,
    verses_count: 77,
  },
  {
    id: 26,
    revelation_place: "makkah",
    name_arabic: "الشعراء",
    start_page: 367,
    end_page: 376,
    verses_count: 227,
  },
  {
    id: 27,
    revelation_place: "makkah",
    name_arabic: "النمل",
    start_page: 377,
    end_page: 385,
    verses_count: 93,
  },
  {
    id: 28,
    revelation_place: "makkah",
    name_arabic: "القصص",
    start_page: 385,
    end_page: 396,
    verses_count: 88,
  },
  {
    id: 29,
    revelation_place: "makkah",
    name_arabic: "العنكبوت",
    start_page: 396,
    end_page: 404,
    verses_count: 69,
  },
  {
    id: 30,
    revelation_place: "makkah",
    name_arabic: "الروم",
    start_page: 404,
    end_page: 410,
    verses_count: 60,
  },
  {
    id: 31,
    revelation_place: "makkah",
    name_arabic: "لقمان",
    start_page: 411,
    end_page: 414,
    verses_count: 34,
  },
  {
    id: 32,
    revelation_place: "makkah",
    name_arabic: "السجدة",
    start_page: 415,
    end_page: 417,
    verses_count: 30,
  },
  {
    id: 33,
    revelation_place: "madinah",
    name_arabic: "الأحزاب",
    start_page: 418,
    end_page: 427,
    verses_count: 73,
  },
  {
    id: 34,
    revelation_place: "makkah",
    name_arabic: "سبإ",
    start_page: 428,
    end_page: 434,
    verses_count: 54,
  },
  {
    id: 35,
    revelation_place: "makkah",
    name_arabic: "فاطر",
    start_page: 434,
    end_page: 440,
    verses_count: 45,
  },
  {
    id: 36,
    revelation_place: "makkah",
    name_arabic: "يس",
    start_page: 440,
    end_page: 445,
    verses_count: 83,
  },
  {
    id: 37,
    revelation_place: "makkah",
    name_arabic: "الصافات",
    start_page: 446,
    end_page: 452,
    verses_count: 182,
  },
  {
    id: 38,
    revelation_place: "makkah",
    name_arabic: "ص",
    start_page: 453,
    end_page: 458,
    verses_count: 88,
  },
  {
    id: 39,
    revelation_place: "makkah",
    name_arabic: "الزمر",
    start_page: 459,
    end_page: 467,
    verses_count: 75,
  },
  {
    id: 40,
    revelation_place: "makkah",
    name_arabic: "غافر",
    start_page: 467,
    end_page: 476,
    verses_count: 85,
  },
  {
    id: 41,
    revelation_place: "makkah",
    name_arabic: "فصلت",
    start_page: 477,
    end_page: 482,
    verses_count: 54,
  },
  {
    id: 42,
    revelation_place: "makkah",
    name_arabic: "الشورى",
    start_page: 483,
    end_page: 489,
    verses_count: 53,
  },
  {
    id: 43,
    revelation_place: "makkah",
    name_arabic: "الزخرف",
    start_page: 489,
    end_page: 495,
    verses_count: 89,
  },
  {
    id: 44,
    revelation_place: "makkah",
    name_arabic: "الدخان",
    start_page: 496,
    end_page: 498,
    verses_count: 59,
  },
  {
    id: 45,
    revelation_place: "makkah",
    name_arabic: "الجاثية",
    start_page: 499,
    end_page: 502,
    verses_count: 37,
  },
  {
    id: 46,
    revelation_place: "makkah",
    name_arabic: "الأحقاف",
    start_page: 502,
    end_page: 506,
    verses_count: 35,
  },
  {
    id: 47,
    revelation_place: "madinah",
    name_arabic: "محمد",
    start_page: 507,
    end_page: 510,
    verses_count: 38,
  },
  {
    id: 48,
    revelation_place: "madinah",
    name_arabic: "الفتح",
    start_page: 511,
    end_page: 515,
    verses_count: 29,
  },
  {
    id: 49,
    revelation_place: "madinah",
    name_arabic: "الحجرات",
    start_page: 515,
    end_page: 517,
    verses_count: 18,
  },
  {
    id: 50,
    revelation_place: "makkah",
    name_arabic: "ق",
    start_page: 518,
    end_page: 520,
    verses_count: 45,
  },
  {
    id: 51,
    revelation_place: "makkah",
    name_arabic: "الذاريات",
    start_page: 520,
    end_page: 523,
    verses_count: 60,
  },
  {
    id: 52,
    revelation_place: "makkah",
    name_arabic: "الطور",
    start_page: 523,
    end_page: 525,
    verses_count: 49,
  },
  {
    id: 53,
    revelation_place: "makkah",
    name_arabic: "النجم",
    start_page: 526,
    end_page: 528,
    verses_count: 62,
  },
  {
    id: 54,
    revelation_place: "makkah",
    name_arabic: "القمر",
    start_page: 528,
    end_page: 531,
    verses_count: 55,
  },
  {
    id: 55,
    revelation_place: "madinah",
    name_arabic: "الرحمن",
    start_page: 531,
    end_page: 534,
    verses_count: 78,
  },
  {
    id: 56,
    revelation_place: "makkah",
    name_arabic: "الواقعة",
    start_page: 534,
    end_page: 537,
    verses_count: 96,
  },
  {
    id: 57,
    revelation_place: "madinah",
    name_arabic: "الحديد",
    start_page: 537,
    end_page: 541,
    verses_count: 29,
  },
  {
    id: 58,
    revelation_place: "madinah",
    name_arabic: "المجادلة",
    start_page: 542,
    end_page: 545,
    verses_count: 22,
  },
  {
    id: 59,
    revelation_place: "madinah",
    name_arabic: "الحشر",
    start_page: 545,
    end_page: 548,
    verses_count: 24,
  },
  {
    id: 60,
    revelation_place: "madinah",
    name_arabic: "الممتحنة",
    start_page: 549,
    end_page: 551,
    verses_count: 13,
  },
  {
    id: 61,
    revelation_place: "madinah",
    name_arabic: "الصف",
    start_page: 551,
    end_page: 552,
    verses_count: 14,
  },
  {
    id: 62,
    revelation_place: "madinah",
    name_arabic: "الجمعة",
    start_page: 553,
    end_page: 554,
    verses_count: 11,
  },
  {
    id: 63,
    revelation_place: "madinah",
    name_arabic: "المنافقون",
    start_page: 554,
    end_page: 555,
    verses_count: 11,
  },
  {
    id: 64,
    revelation_place: "madinah",
    name_arabic: "التغابن",
    start_page: 556,
    end_page: 558,
    verses_count: 18,
  },
  {
    id: 65,
    revelation_place: "madinah",
    name_arabic: "الطلاق",
    start_page: 558,
    end_page: 560,
    verses_count: 12,
  },
  {
    id: 66,
    revelation_place: "madinah",
    name_arabic: "التحريم",
    start_page: 560,
    end_page: 562,
    verses_count: 12,
  },
  {
    id: 67,
    revelation_place: "makkah",
    name_arabic: "الملك",
    start_page: 562,
    end_page: 564,
    verses_count: 30,
  },
  {
    id: 68,
    revelation_place: "makkah",
    name_arabic: "القلم",
    start_page: 564,
    end_page: 566,
    verses_count: 52,
  },
  {
    id: 69,
    revelation_place: "makkah",
    name_arabic: "الحاقة",
    start_page: 566,
    end_page: 568,
    verses_count: 52,
  },
  {
    id: 70,
    revelation_place: "makkah",
    name_arabic: "المعارج",
    start_page: 568,
    end_page: 570,
    verses_count: 44,
  },
  {
    id: 71,
    revelation_place: "makkah",
    name_arabic: "نوح",
    start_page: 570,
    end_page: 571,
    verses_count: 28,
  },
  {
    id: 72,
    revelation_place: "makkah",
    name_arabic: "الجن",
    start_page: 572,
    end_page: 573,
    verses_count: 28,
  },
  {
    id: 73,
    revelation_place: "makkah",
    name_arabic: "المزمل",
    start_page: 574,
    end_page: 575,
    verses_count: 20,
  },
  {
    id: 74,
    revelation_place: "makkah",
    name_arabic: "المدثر",
    start_page: 575,
    end_page: 577,
    verses_count: 56,
  },
  {
    id: 75,
    revelation_place: "makkah",
    name_arabic: "القيامة",
    start_page: 577,
    end_page: 578,
    verses_count: 40,
  },
  {
    id: 76,
    revelation_place: "madinah",
    name_arabic: "الإنسان",
    start_page: 578,
    end_page: 580,
    verses_count: 31,
  },
  {
    id: 77,
    revelation_place: "makkah",
    name_arabic: "المرسلات",
    start_page: 580,
    end_page: 581,
    verses_count: 50,
  },
  {
    id: 78,
    revelation_place: "makkah",
    name_arabic: "النبأ",
    start_page: 582,
    end_page: 583,
    verses_count: 40,
  },
  {
    id: 79,
    revelation_place: "makkah",
    name_arabic: "النازعات",
    start_page: 583,
    end_page: 584,
    verses_count: 46,
  },
  {
    id: 80,
    revelation_place: "makkah",
    name_arabic: "عبس",
    start_page: 585,
    end_page: 586,
    verses_count: 42,
  },
  {
    id: 81,
    revelation_place: "makkah",
    name_arabic: "التكوير",
    start_page: 586,
    end_page: 587,
    verses_count: 29,
  },
  {
    id: 82,
    revelation_place: "makkah",
    name_arabic: "الإنفطار",
    start_page: 587,
    end_page: 587,
    verses_count: 19,
  },
  {
    id: 83,
    revelation_place: "makkah",
    name_arabic: "المطففين",
    start_page: 588,
    end_page: 589,
    verses_count: 36,
  },
  {
    id: 84,
    revelation_place: "makkah",
    name_arabic: "الإنشقاق",
    start_page: 589,
    end_page: 590,
    verses_count: 25,
  },
  {
    id: 85,
    revelation_place: "makkah",
    name_arabic: "البروج",
    start_page: 590,
    end_page: 590,
    verses_count: 22,
  },
  {
    id: 86,
    revelation_place: "makkah",
    name_arabic: "الطارق",
    start_page: 591,
    end_page: 591,
    verses_count: 17,
  },
  {
    id: 87,
    revelation_place: "makkah",
    name_arabic: "الأعلى",
    start_page: 591,
    end_page: 592,
    verses_count: 19,
  },
  {
    id: 88,
    revelation_place: "makkah",
    name_arabic: "الغاشية",
    start_page: 592,
    end_page: 593,
    verses_count: 26,
  },
  {
    id: 89,
    revelation_place: "makkah",
    name_arabic: "الفجر",
    start_page: 593,
    end_page: 594,
    verses_count: 30,
  },
  {
    id: 90,
    revelation_place: "makkah",
    name_arabic: "البلد",
    start_page: 594,
    end_page: 595,
    verses_count: 20,
  },
  {
    id: 91,
    revelation_place: "makkah",
    name_arabic: "الشمس",
    start_page: 595,
    end_page: 595,
    verses_count: 15,
  },
  {
    id: 92,
    revelation_place: "makkah",
    name_arabic: "الليل",
    start_page: 596,
    end_page: 596,
    verses_count: 21,
  },
  {
    id: 93,
    revelation_place: "makkah",
    name_arabic: "الضحى",
    start_page: 596,
    end_page: 596,
    verses_count: 11,
  },
  {
    id: 94,
    revelation_place: "makkah",
    name_arabic: "الشرح",
    start_page: 596,
    end_page: 597,
    verses_count: 8,
  },
  {
    id: 95,
    revelation_place: "makkah",
    name_arabic: "التين",
    start_page: 597,
    end_page: 597,
    verses_count: 8,
  },
  {
    id: 96,
    revelation_place: "makkah",
    name_arabic: "العلق",
    start_page: 597,
    end_page: 598,
    verses_count: 19,
  },
  {
    id: 97,
    revelation_place: "makkah",
    name_arabic: "القدر",
    start_page: 598,
    end_page: 598,
    verses_count: 5,
  },
  {
    id: 98,
    revelation_place: "madinah",
    name_arabic: "البينة",
    start_page: 599,
    end_page: 599,
    verses_count: 8,
  },
  {
    id: 99,
    revelation_place: "madinah",
    name_arabic: "الزلزلة",
    start_page: 599,
    end_page: 599,
    verses_count: 8,
  },
  {
    id: 100,
    revelation_place: "madinah",
    name_arabic: "العاديات",
    start_page: 600,
    end_page: 600,
    verses_count: 11,
  },
  {
    id: 101,
    revelation_place: "makkah",
    name_arabic: "القارعة",
    start_page: 600,
    end_page: 600,
    verses_count: 11,
  },
  {
    id: 102,
    revelation_place: "makkah",
    name_arabic: "التكاثر",
    start_page: 601,
    end_page: 601,
    verses_count: 8,
  },
  {
    id: 103,
    revelation_place: "makkah",
    name_arabic: "العصر",
    start_page: 601,
    end_page: 601,
    verses_count: 3,
  },
  {
    id: 104,
    revelation_place: "makkah",
    name_arabic: "الهمزة",
    start_page: 601,
    end_page: 601,
    verses_count: 9,
  },
  {
    id: 105,
    revelation_place: "makkah",
    name_arabic: "الفيل",
    start_page: 602,
    end_page: 602,
    verses_count: 5,
  },
  {
    id: 106,
    revelation_place: "makkah",
    name_arabic: "قريش",
    start_page: 602,
    end_page: 602,
    verses_count: 4,
  },
  {
    id: 107,
    revelation_place: "makkah",
    name_arabic: "الماعون",
    start_page: 602,
    end_page: 602,
    verses_count: 7,
  },
  {
    id: 108,
    revelation_place: "makkah",
    name_arabic: "الكوثر",
    start_page: 603,
    end_page: 603,
    verses_count: 3,
  },
  {
    id: 109,
    revelation_place: "makkah",
    name_arabic: "الكافرون",
    start_page: 603,
    end_page: 603,
    verses_count: 6,
  },
  {
    id: 110,
    revelation_place: "madinah",
    name_arabic: "النصر",
    start_page: 603,
    end_page: 603,
    verses_count: 3,
  },
  {
    id: 111,
    revelation_place: "makkah",
    name_arabic: "المسد",
    start_page: 604,
    end_page: 604,
    verses_count: 5,
  },
  {
    id: 112,
    revelation_place: "makkah",
    name_arabic: "الإخلاص",
    start_page: 604,
    end_page: 604,
    verses_count: 4,
  },
  {
    id: 113,
    revelation_place: "makkah",
    name_arabic: "الفلق",
    start_page: 604,
    end_page: 604,
    verses_count: 5,
  },
  {
    id: 114,
    revelation_place: "makkah",
    name_arabic: "الناس",
    start_page: 604,
    end_page: 605,
    verses_count: 6,
  },
];
