export const surahsData = [
  {
    id: 1,
    revelation_place: "makkah",
    name_arabic: "الفاتحة",
    name_code: "]",
    start_page: 1,
    end_page: 1,
    verses_count: 7,
    pre_bismillah: false,
  },
  {
    id: 2,
    revelation_place: "madinah",
    name_arabic: "البقرة",
    name_code: "^",
    start_page: 2,
    end_page: 49,
    verses_count: 286,
    pre_bismillah: true,
  },
  {
    id: 3,
    revelation_place: "madinah",
    name_arabic: "آل عمران",
    name_code: "_",
    start_page: 50,
    end_page: 76,
    verses_count: 200,
    pre_bismillah: true,
  },
  {
    id: 4,
    revelation_place: "madinah",
    name_arabic: "النساء",
    name_code: "`",
    start_page: 77,
    end_page: 106,
    verses_count: 176,
    pre_bismillah: true,
  },
  {
    id: 5,
    revelation_place: "madinah",
    name_arabic: "المائدة",
    name_code: "a",
    start_page: 106,
    end_page: 127,
    verses_count: 120,
    pre_bismillah: true,
  },
  {
    id: 6,
    revelation_place: "makkah",
    name_arabic: "الأنعام",
    name_code: "b",
    start_page: 128,
    end_page: 150,
    verses_count: 165,
    pre_bismillah: true,
  },
  {
    id: 7,
    revelation_place: "makkah",
    name_arabic: "الأعراف",
    name_code: "c",
    start_page: 151,
    end_page: 176,
    verses_count: 206,
    pre_bismillah: true,
  },
  {
    id: 8,
    revelation_place: "madinah",
    name_arabic: "الأنفال",
    name_code: "d",
    start_page: 177,
    end_page: 186,
    verses_count: 75,
    pre_bismillah: true,
  },
  {
    id: 9,
    revelation_place: "madinah",
    name_arabic: "التوبة",
    name_code: "e",
    start_page: 187,
    end_page: 207,
    verses_count: 129,
    pre_bismillah: false,
  },
  {
    id: 10,
    revelation_place: "makkah",
    name_arabic: "يونس",
    name_code: "f",
    start_page: 208,
    end_page: 221,
    verses_count: 109,
    pre_bismillah: true,
  },
  {
    id: 11,
    revelation_place: "makkah",
    name_arabic: "هود",
    name_code: "g",
    start_page: 221,
    end_page: 235,
    verses_count: 123,
    pre_bismillah: true,
  },
  {
    id: 12,
    revelation_place: "makkah",
    name_arabic: "يوسف",
    name_code: "h",
    start_page: 235,
    end_page: 248,
    verses_count: 111,
    pre_bismillah: true,
  },
  {
    id: 13,
    revelation_place: "madinah",
    name_arabic: "الرعد",
    name_code: "i",
    start_page: 249,
    end_page: 255,
    verses_count: 43,
    pre_bismillah: true,
  },
  {
    id: 14,
    revelation_place: "makkah",
    name_arabic: "ابراهيم",
    name_code: "j",
    start_page: 255,
    end_page: 261,
    verses_count: 52,
    pre_bismillah: true,
  },
  {
    id: 15,
    revelation_place: "makkah",
    name_arabic: "الحجر",
    name_code: "k",
    start_page: 262,
    end_page: 267,
    verses_count: 99,
    pre_bismillah: true,
  },
  {
    id: 16,
    revelation_place: "makkah",
    name_arabic: "النحل",
    name_code: "l",
    start_page: 267,
    end_page: 281,
    verses_count: 128,
    pre_bismillah: true,
  },
  {
    id: 17,
    revelation_place: "makkah",
    name_arabic: "الإسراء",
    name_code: "m",
    start_page: 282,
    end_page: 293,
    verses_count: 111,
    pre_bismillah: true,
  },
  {
    id: 18,
    revelation_place: "makkah",
    name_arabic: "الكهف",
    name_code: "n",
    start_page: 293,
    end_page: 304,
    verses_count: 110,
    pre_bismillah: true,
  },
  {
    id: 19,
    revelation_place: "makkah",
    name_arabic: "مريم",
    name_code: "o",
    start_page: 305,
    end_page: 312,
    verses_count: 98,
    pre_bismillah: true,
  },
  {
    id: 20,
    revelation_place: "makkah",
    name_arabic: "طه",
    name_code: "p",
    start_page: 312,
    end_page: 321,
    verses_count: 135,
    pre_bismillah: true,
  },
  {
    id: 21,
    revelation_place: "makkah",
    name_arabic: "الأنبياء",
    name_code: "q",
    start_page: 322,
    end_page: 331,
    verses_count: 112,
    pre_bismillah: true,
  },
  {
    id: 22,
    revelation_place: "madinah",
    name_arabic: "الحج",
    name_code: "r",
    start_page: 332,
    end_page: 341,
    verses_count: 78,
    pre_bismillah: true,
  },
  {
    id: 23,
    revelation_place: "makkah",
    name_arabic: "المؤمنون",
    name_code: "s",
    start_page: 342,
    end_page: 349,
    verses_count: 118,
    pre_bismillah: true,
  },
  {
    id: 24,
    revelation_place: "madinah",
    name_arabic: "النور",
    name_code: "t",
    start_page: 350,
    end_page: 359,
    verses_count: 64,
    pre_bismillah: true,
  },
  {
    id: 25,
    revelation_place: "makkah",
    name_arabic: "الفرقان",
    name_code: "u",
    start_page: 359,
    end_page: 366,
    verses_count: 77,
    pre_bismillah: true,
  },
  {
    id: 26,
    revelation_place: "makkah",
    name_arabic: "الشعراء",
    name_code: "v",
    start_page: 367,
    end_page: 376,
    verses_count: 227,
    pre_bismillah: true,
  },
  {
    id: 27,
    revelation_place: "makkah",
    name_arabic: "النمل",
    name_code: "w",
    start_page: 377,
    end_page: 385,
    verses_count: 93,
    pre_bismillah: true,
  },
  {
    id: 28,
    revelation_place: "makkah",
    name_arabic: "القصص",
    name_code: "x",
    start_page: 385,
    end_page: 396,
    verses_count: 88,
    pre_bismillah: true,
  },
  {
    id: 29,
    revelation_place: "makkah",
    name_arabic: "العنكبوت",
    name_code: "y",
    start_page: 396,
    end_page: 404,
    verses_count: 69,
    pre_bismillah: true,
  },
  {
    id: 30,
    revelation_place: "makkah",
    name_arabic: "الروم",
    name_code: "z",
    start_page: 404,
    end_page: 410,
    verses_count: 60,
    pre_bismillah: true,
  },
  {
    id: 31,
    revelation_place: "makkah",
    name_arabic: "لقمان",
    name_code: "{",
    start_page: 411,
    end_page: 414,
    verses_count: 34,
    pre_bismillah: true,
  },
  {
    id: 32,
    revelation_place: "makkah",
    name_arabic: "السجدة",
    name_code: "ﮬ",
    start_page: 415,
    end_page: 417,
    verses_count: 30,
    pre_bismillah: true,
  },
  {
    id: 33,
    revelation_place: "madinah",
    name_arabic: "الأحزاب",
    name_code: "}",
    start_page: 418,
    end_page: 427,
    verses_count: 73,
    pre_bismillah: true,
  },
  {
    id: 34,
    revelation_place: "makkah",
    name_arabic: "سبإ",
    name_code: "~",
    start_page: 428,
    end_page: 434,
    verses_count: 54,
    pre_bismillah: true,
  },
  {
    id: 35,
    revelation_place: "makkah",
    name_arabic: "فاطر",
    name_code: "ﮯ",
    start_page: 434,
    end_page: 440,
    verses_count: 45,
    pre_bismillah: true,
  },
  {
    id: 36,
    revelation_place: "makkah",
    name_arabic: "يس",
    name_code: "¡",
    start_page: 440,
    end_page: 445,
    verses_count: 83,
    pre_bismillah: true,
  },
  {
    id: 37,
    revelation_place: "makkah",
    name_arabic: "الصافات",
    name_code: "¢",
    start_page: 446,
    end_page: 452,
    verses_count: 182,
    pre_bismillah: true,
  },
  {
    id: 38,
    revelation_place: "makkah",
    name_arabic: "ص",
    name_code: "£",
    start_page: 453,
    end_page: 458,
    verses_count: 88,
    pre_bismillah: true,
  },
  {
    id: 39,
    revelation_place: "makkah",
    name_arabic: "الزمر",
    name_code: "¤",
    start_page: 459,
    end_page: 467,
    verses_count: 75,
    pre_bismillah: true,
  },
  {
    id: 40,
    revelation_place: "makkah",
    name_arabic: "غافر",
    name_code: "¥",
    start_page: 467,
    end_page: 476,
    verses_count: 85,
    pre_bismillah: true,
  },
  {
    id: 41,
    revelation_place: "makkah",
    name_arabic: "فصلت",
    name_code: "¦",
    start_page: 477,
    end_page: 482,
    verses_count: 54,
    pre_bismillah: true,
  },
  {
    id: 42,
    revelation_place: "makkah",
    name_arabic: "الشورى",
    name_code: "§",
    start_page: 483,
    end_page: 489,
    verses_count: 53,
    pre_bismillah: true,
  },
  {
    id: 43,
    revelation_place: "makkah",
    name_arabic: "الزخرف",
    name_code: "¨",
    start_page: 489,
    end_page: 495,
    verses_count: 89,
    pre_bismillah: true,
  },
  {
    id: 44,
    revelation_place: "makkah",
    name_arabic: "الدخان",
    name_code: "©",
    start_page: 496,
    end_page: 498,
    verses_count: 59,
    pre_bismillah: true,
  },
  {
    id: 45,
    revelation_place: "makkah",
    name_arabic: "الجاثية",
    name_code: "ª",
    start_page: 499,
    end_page: 502,
    verses_count: 37,
    pre_bismillah: true,
  },
  {
    id: 46,
    revelation_place: "makkah",
    name_arabic: "الأحقاف",
    name_code: "«",
    start_page: 502,
    end_page: 506,
    verses_count: 35,
    pre_bismillah: true,
  },
  {
    id: 47,
    revelation_place: "madinah",
    name_arabic: "محمد",
    name_code: "¬",
    start_page: 507,
    end_page: 510,
    verses_count: 38,
    pre_bismillah: true,
  },
  {
    id: 48,
    revelation_place: "madinah",
    name_arabic: "الفتح",
    name_code: "®",
    start_page: 511,
    end_page: 515,
    verses_count: 29,
    pre_bismillah: true,
  },
  {
    id: 49,
    revelation_place: "madinah",
    name_arabic: "الحجرات",
    name_code: "¯",
    start_page: 515,
    end_page: 517,
    verses_count: 18,
    pre_bismillah: true,
  },
  {
    id: 50,
    revelation_place: "makkah",
    name_arabic: "ق",
    name_code: "°",
    start_page: 518,
    end_page: 520,
    verses_count: 45,
    pre_bismillah: true,
  },
  {
    id: 51,
    revelation_place: "makkah",
    name_arabic: "الذاريات",
    name_code: "±",
    start_page: 520,
    end_page: 523,
    verses_count: 60,
    pre_bismillah: true,
  },
  {
    id: 52,
    revelation_place: "makkah",
    name_arabic: "الطور",
    name_code: "²",
    start_page: 523,
    end_page: 525,
    verses_count: 49,
    pre_bismillah: true,
  },
  {
    id: 53,
    revelation_place: "makkah",
    name_arabic: "النجم",
    name_code: "³",
    start_page: 526,
    end_page: 528,
    verses_count: 62,
    pre_bismillah: true,
  },
  {
    id: 54,
    revelation_place: "makkah",
    name_arabic: "القمر",
    name_code: "´",
    start_page: 528,
    end_page: 531,
    verses_count: 55,
    pre_bismillah: true,
  },
  {
    id: 55,
    revelation_place: "madinah",
    name_arabic: "الرحمن",
    name_code: "µ",
    start_page: 531,
    end_page: 534,
    verses_count: 78,
    pre_bismillah: true,
  },
  {
    id: 56,
    revelation_place: "makkah",
    name_arabic: "الواقعة",
    name_code: "¶",
    start_page: 534,
    end_page: 537,
    verses_count: 96,
    pre_bismillah: true,
  },
  {
    id: 57,
    revelation_place: "madinah",
    name_arabic: "الحديد",
    name_code: "¸",
    start_page: 537,
    end_page: 541,
    verses_count: 29,
    pre_bismillah: true,
  },
  {
    id: 58,
    revelation_place: "madinah",
    name_arabic: "المجادلة",
    name_code: "¹",
    start_page: 542,
    end_page: 545,
    verses_count: 22,
    pre_bismillah: true,
  },
  {
    id: 59,
    revelation_place: "madinah",
    name_arabic: "الحشر",
    name_code: "º",
    start_page: 545,
    end_page: 548,
    verses_count: 24,
    pre_bismillah: true,
  },
  {
    id: 60,
    revelation_place: "madinah",
    name_arabic: "الممتحنة",
    name_code: "»",
    start_page: 549,
    end_page: 551,
    verses_count: 13,
    pre_bismillah: true,
  },
  {
    id: 61,
    revelation_place: "madinah",
    name_arabic: "الصف",
    name_code: "¼",
    start_page: 551,
    end_page: 552,
    verses_count: 14,
    pre_bismillah: true,
  },
  {
    id: 62,
    revelation_place: "madinah",
    name_arabic: "الجمعة",
    name_code: "½",
    start_page: 553,
    end_page: 554,
    verses_count: 11,
    pre_bismillah: true,
  },
  {
    id: 63,
    revelation_place: "madinah",
    name_arabic: "المنافقون",
    name_code: "¾",
    start_page: 554,
    end_page: 555,
    verses_count: 11,
    pre_bismillah: true,
  },
  {
    id: 64,
    revelation_place: "madinah",
    name_arabic: "التغابن",
    name_code: "¿",
    start_page: 556,
    end_page: 558,
    verses_count: 18,
    pre_bismillah: true,
  },
  {
    id: 65,
    revelation_place: "madinah",
    name_arabic: "الطلاق",
    name_code: "À",
    start_page: 558,
    end_page: 560,
    verses_count: 12,
    pre_bismillah: true,
  },
  {
    id: 66,
    revelation_place: "madinah",
    name_arabic: "التحريم",
    name_code: "Á",
    start_page: 560,
    end_page: 562,
    verses_count: 12,
    pre_bismillah: true,
  },
  {
    id: 67,
    revelation_place: "makkah",
    name_arabic: "الملك",
    name_code: "Â",
    start_page: 562,
    end_page: 564,
    verses_count: 30,
    pre_bismillah: true,
  },
  {
    id: 68,
    revelation_place: "makkah",
    name_arabic: "القلم",
    name_code: "Ã",
    start_page: 564,
    end_page: 566,
    verses_count: 52,
    pre_bismillah: true,
  },
  {
    id: 69,
    revelation_place: "makkah",
    name_arabic: "الحاقة",
    name_code: "Ä",
    start_page: 566,
    end_page: 568,
    verses_count: 52,
    pre_bismillah: true,
  },
  {
    id: 70,
    revelation_place: "makkah",
    name_arabic: "المعارج",
    name_code: "Å",
    start_page: 568,
    end_page: 570,
    verses_count: 44,
    pre_bismillah: true,
  },
  {
    id: 71,
    revelation_place: "makkah",
    name_arabic: "نوح",
    name_code: "Æ",
    start_page: 570,
    end_page: 571,
    verses_count: 28,
    pre_bismillah: true,
  },
  {
    id: 72,
    revelation_place: "makkah",
    name_arabic: "الجن",
    name_code: "Ç",
    start_page: 572,
    end_page: 573,
    verses_count: 28,
    pre_bismillah: true,
  },
  {
    id: 73,
    revelation_place: "makkah",
    name_arabic: "المزمل",
    name_code: "È",
    start_page: 574,
    end_page: 575,
    verses_count: 20,
    pre_bismillah: true,
  },
  {
    id: 74,
    revelation_place: "makkah",
    name_arabic: "المدثر",
    name_code: "É",
    start_page: 575,
    end_page: 577,
    verses_count: 56,
    pre_bismillah: true,
  },
  {
    id: 75,
    revelation_place: "makkah",
    name_arabic: "القيامة",
    name_code: "Ê",
    start_page: 577,
    end_page: 578,
    verses_count: 40,
    pre_bismillah: true,
  },
  {
    id: 76,
    revelation_place: "madinah",
    name_arabic: "الإنسان",
    name_code: "Ë",
    start_page: 578,
    end_page: 580,
    verses_count: 31,
    pre_bismillah: true,
  },
  {
    id: 77,
    revelation_place: "makkah",
    name_arabic: "المرسلات",
    name_code: "Ì",
    start_page: 580,
    end_page: 581,
    verses_count: 50,
    pre_bismillah: true,
  },
  {
    id: 78,
    revelation_place: "makkah",
    name_arabic: "النبأ",
    name_code: "Í",
    start_page: 582,
    end_page: 583,
    verses_count: 40,
    pre_bismillah: true,
  },
  {
    id: 79,
    revelation_place: "makkah",
    name_arabic: "النازعات",
    name_code: "Î",
    start_page: 583,
    end_page: 584,
    verses_count: 46,
    pre_bismillah: true,
  },
  {
    id: 80,
    revelation_place: "makkah",
    name_arabic: "عبس",
    name_code: "Ï",
    start_page: 585,
    end_page: 586,
    verses_count: 42,
    pre_bismillah: true,
  },
  {
    id: 81,
    revelation_place: "makkah",
    name_arabic: "التكوير",
    name_code: "Ð",
    start_page: 586,
    end_page: 587,
    verses_count: 29,
    pre_bismillah: true,
  },
  {
    id: 82,
    revelation_place: "makkah",
    name_arabic: "الإنفطار",
    name_code: "Ñ",
    start_page: 587,
    end_page: 587,
    verses_count: 19,
    pre_bismillah: true,
  },
  {
    id: 83,
    revelation_place: "makkah",
    name_arabic: "المطففين",
    name_code: "Ò",
    start_page: 588,
    end_page: 589,
    verses_count: 36,
    pre_bismillah: true,
  },
  {
    id: 84,
    revelation_place: "makkah",
    name_arabic: "الإنشقاق",
    name_code: "Ó",
    start_page: 589,
    end_page: 590,
    verses_count: 25,
    pre_bismillah: true,
  },
  {
    id: 85,
    revelation_place: "makkah",
    name_arabic: "البروج",
    name_code: "Ô",
    start_page: 590,
    end_page: 590,
    verses_count: 22,
    pre_bismillah: true,
  },
  {
    id: 86,
    revelation_place: "makkah",
    name_arabic: "الطارق",
    name_code: "Õ",
    start_page: 591,
    end_page: 591,
    verses_count: 17,
    pre_bismillah: true,
  },
  {
    id: 87,
    revelation_place: "makkah",
    name_arabic: "الأعلى",
    name_code: "Ö",
    start_page: 591,
    end_page: 592,
    verses_count: 19,
    pre_bismillah: true,
  },
  {
    id: 88,
    revelation_place: "makkah",
    name_arabic: "الغاشية",
    name_code: "×",
    start_page: 592,
    end_page: 593,
    verses_count: 26,
    pre_bismillah: true,
  },
  {
    id: 89,
    revelation_place: "makkah",
    name_arabic: "الفجر",
    name_code: "Ø",
    start_page: 593,
    end_page: 594,
    verses_count: 30,
    pre_bismillah: true,
  },
  {
    id: 90,
    revelation_place: "makkah",
    name_arabic: "البلد",
    name_code: "Ù",
    start_page: 594,
    end_page: 595,
    verses_count: 20,
    pre_bismillah: true,
  },
  {
    id: 91,
    revelation_place: "makkah",
    name_arabic: "الشمس",
    name_code: "Ú",
    start_page: 595,
    end_page: 595,
    verses_count: 15,
    pre_bismillah: true,
  },
  {
    id: 92,
    revelation_place: "makkah",
    name_arabic: "الليل",
    name_code: "Û",
    start_page: 596,
    end_page: 596,
    verses_count: 21,
    pre_bismillah: true,
  },
  {
    id: 93,
    revelation_place: "makkah",
    name_arabic: "الضحى",
    name_code: "Ü",
    start_page: 596,
    end_page: 596,
    verses_count: 11,
    pre_bismillah: true,
  },
  {
    id: 94,
    revelation_place: "makkah",
    name_arabic: "الشرح",
    name_code: "Ý",
    start_page: 596,
    end_page: 597,
    verses_count: 8,
    pre_bismillah: true,
  },
  {
    id: 95,
    revelation_place: "makkah",
    name_arabic: "التين",
    name_code: "Þ",
    start_page: 597,
    end_page: 597,
    verses_count: 8,
    pre_bismillah: true,
  },
  {
    id: 96,
    revelation_place: "makkah",
    name_arabic: "العلق",
    name_code: "ß",
    start_page: 597,
    end_page: 598,
    verses_count: 19,
    pre_bismillah: true,
  },
  {
    id: 97,
    revelation_place: "makkah",
    name_arabic: "القدر",
    name_code: "à",
    start_page: 598,
    end_page: 598,
    verses_count: 5,
    pre_bismillah: true,
  },
  {
    id: 98,
    revelation_place: "madinah",
    name_arabic: "البينة",
    name_code: "á",
    start_page: 599,
    end_page: 599,
    verses_count: 8,
    pre_bismillah: true,
  },
  {
    id: 99,
    revelation_place: "madinah",
    name_arabic: "الزلزلة",
    name_code: "â",
    start_page: 599,
    end_page: 599,
    verses_count: 8,
    pre_bismillah: true,
  },
  {
    id: 100,
    revelation_place: "madinah",
    name_arabic: "العاديات",
    name_code: "ã",
    start_page: 600,
    end_page: 600,
    verses_count: 11,
    pre_bismillah: true,
  },
  {
    id: 101,
    revelation_place: "makkah",
    name_arabic: "القارعة",
    name_code: "ä",
    start_page: 600,
    end_page: 600,
    verses_count: 11,
    pre_bismillah: true,
  },
  {
    id: 102,
    revelation_place: "makkah",
    name_arabic: "التكاثر",
    name_code: "å",
    start_page: 601,
    end_page: 601,
    verses_count: 8,
    pre_bismillah: true,
  },
  {
    id: 103,
    revelation_place: "makkah",
    name_arabic: "العصر",
    name_code: "æ",
    start_page: 601,
    end_page: 601,
    verses_count: 3,
    pre_bismillah: true,
  },
  {
    id: 104,
    revelation_place: "makkah",
    name_arabic: "الهمزة",
    name_code: "ç",
    start_page: 601,
    end_page: 601,
    verses_count: 9,
    pre_bismillah: true,
  },
  {
    id: 105,
    revelation_place: "makkah",
    name_arabic: "الفيل",
    name_code: "è",
    start_page: 602,
    end_page: 602,
    verses_count: 5,
    pre_bismillah: true,
  },
  {
    id: 106,
    revelation_place: "makkah",
    name_arabic: "قريش",
    name_code: "é",
    start_page: 602,
    end_page: 602,
    verses_count: 4,
    pre_bismillah: true,
  },
  {
    id: 107,
    revelation_place: "makkah",
    name_arabic: "الماعون",
    name_code: "ê",
    start_page: 602,
    end_page: 602,
    verses_count: 7,
    pre_bismillah: true,
  },
  {
    id: 108,
    revelation_place: "makkah",
    name_arabic: "الكوثر",
    name_code: "ë",
    start_page: 603,
    end_page: 603,
    verses_count: 3,
    pre_bismillah: true,
  },
  {
    id: 109,
    revelation_place: "makkah",
    name_arabic: "الكافرون",
    name_code: "ì",
    start_page: 603,
    end_page: 603,
    verses_count: 6,
    pre_bismillah: true,
  },
  {
    id: 110,
    revelation_place: "madinah",
    name_arabic: "النصر",
    name_code: "í",
    start_page: 603,
    end_page: 603,
    verses_count: 3,
    pre_bismillah: true,
  },
  {
    id: 111,
    revelation_place: "makkah",
    name_arabic: "المسد",
    name_code: "î",
    start_page: 604,
    end_page: 604,
    verses_count: 5,
    pre_bismillah: true,
  },
  {
    id: 112,
    revelation_place: "makkah",
    name_arabic: "الإخلاص",
    name_code: "ï",
    start_page: 604,
    end_page: 604,
    verses_count: 4,
    pre_bismillah: true,
  },
  {
    id: 113,
    revelation_place: "makkah",
    name_arabic: "الفلق",
    name_code: "ð",
    start_page: 604,
    end_page: 604,
    verses_count: 5,
    pre_bismillah: true,
  },
  {
    id: 114,
    revelation_place: "makkah",
    name_arabic: "الناس",
    name_code: "ñ",
    start_page: 604,
    end_page: 604,
    verses_count: 6,
    pre_bismillah: true,
  },
];
